import type {
  ToolAsset,
  FleetVehicle,
  VanStockItem,
  MaintenanceRecord,
} from '@/lib/inventory-tracker';

export const DEFAULT_TOOLS: ToolAsset[] = [
  {
    id: 'tool-1',
    name: 'RIDGID RP 351 ProPress Press Tool',
    category: 'Pipe Joining',
    brand: 'RIDGID',
    modelNumber: 'RP 351',
    serialNumber: 'RP351-884920',
    assetTag: 'TAG-PLUMB-01',
    purchasePrice: 3850,
    purchaseDate: '2025-04-10',
    status: 'checked_out',
    assignedCrewId: 'c1',
    assignedCrewName: 'Jake Martinez',
    assignedJobId: 'job-101',
    assignedJobLabel: 'Water Heater Replacement (142 Ridgewood Rd)',
    checkedOutAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    notes: 'Includes 1/2" to 2" ProPress copper jaws.',
  },
  {
    id: 'tool-2',
    name: 'Spartan 738 Water Jetter 3000 PSI',
    category: 'Drain Cleaning',
    brand: 'Spartan Tool',
    modelNumber: 'Model 738',
    serialNumber: 'SP738-90214',
    assetTag: 'TAG-JETTER-01',
    purchasePrice: 8200,
    purchaseDate: '2024-11-15',
    status: 'available',
    notes: 'Stored in Shop Bay 2. New 250ft sewer hose installed.',
  },
  {
    id: 'tool-3',
    name: 'FLIR E8-XT Infrared Thermal Camera',
    category: 'Diagnostics',
    brand: 'FLIR',
    modelNumber: 'E8-XT',
    serialNumber: 'FLIR-38910-E8',
    assetTag: 'TAG-DIAG-03',
    purchasePrice: 2995,
    purchaseDate: '2025-01-20',
    status: 'available',
    notes: 'Case in central tool cage. Batteries charged.',
  },
  {
    id: 'tool-4',
    name: 'Milwaukee M18 FUEL Deep Cut Band Saw',
    category: 'Cutting Tools',
    brand: 'Milwaukee',
    modelNumber: '2729-20',
    serialNumber: 'MW2729-109283',
    assetTag: 'TAG-CUT-04',
    purchasePrice: 429,
    purchaseDate: '2025-06-05',
    status: 'checked_out',
    assignedCrewId: 'c2',
    assignedCrewName: 'Dave Cooper',
    assignedJobId: 'job-101',
    assignedJobLabel: 'Water Heater Replacement (142 Ridgewood Rd)',
    checkedOutAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'tool-5',
    name: 'Fieldpiece SMAN480V 4-Port Wireless Manifold',
    category: 'HVAC Diagnostics',
    brand: 'Fieldpiece',
    modelNumber: 'SMAN480V',
    serialNumber: 'FP480-77301',
    assetTag: 'TAG-HVAC-02',
    purchasePrice: 845,
    purchaseDate: '2025-03-12',
    status: 'in_maintenance',
    notes: 'Micron sensor calibration in progress at factory service center.',
  },
];

export const DEFAULT_VEHICLES: FleetVehicle[] = [
  {
    id: 'veh-1',
    name: 'Service Truck 1 (Jake)',
    make: 'Ford',
    model: 'F-250 Super Duty SuperCab',
    year: 2024,
    licensePlate: 'X92-KLP',
    vin: '1FT8W2BT5REC99210',
    currentMileage: 24850,
    primaryDriverId: 'c1',
    primaryDriverName: 'Jake Martinez',
    status: 'active',
    lastServiceDate: '2026-05-10',
    lastServiceMileage: 20000,
    nextServiceDueMileage: 25000, // Due in 150 miles!
    inspectionExpiresAt: '2026-11-30',
    insuranceExpiresAt: '2027-04-15',
    notes: 'Equipped with ladder rack, packout shelves, and 100-gal fuel transfer tank.',
  },
  {
    id: 'veh-2',
    name: 'Install Van 2 (Dave)',
    make: 'Ram',
    model: 'ProMaster 2500 High Roof',
    year: 2023,
    licensePlate: 'Y81-MNT',
    vin: '3C6URVBG8PE102938',
    currentMileage: 38400,
    primaryDriverId: 'c2',
    primaryDriverName: 'Dave Cooper',
    status: 'active',
    lastServiceDate: '2026-04-02',
    lastServiceMileage: 35000,
    nextServiceDueMileage: 40000,
    inspectionExpiresAt: '2026-08-15', // Expired recently!
    insuranceExpiresAt: '2027-04-15',
    notes: 'Full plumbing bin shelving layout.',
  },
  {
    id: 'veh-3',
    name: 'HVAC Box Truck 3 (Tyler)',
    make: 'Chevrolet',
    model: 'Express 3500 Cutaway',
    year: 2022,
    licensePlate: 'Z44-QRS',
    vin: '1GB6G3BG6N1920391',
    currentMileage: 52100,
    primaryDriverId: 'c3',
    primaryDriverName: 'Tyler Vance',
    status: 'active',
    lastServiceDate: '2026-02-18',
    lastServiceMileage: 45000,
    nextServiceDueMileage: 50000, // Overdue by 2,100 miles!
    inspectionExpiresAt: '2027-02-28',
    insuranceExpiresAt: '2027-04-15',
    notes: 'Refrigerant recovery station mounted in rear.',
  },
];

export const DEFAULT_VAN_STOCK: VanStockItem[] = [
  {
    id: 'stock-1',
    name: '3/4" Copper ProPress Coupling (Lead-Free)',
    sku: 'VIEGA-78052',
    category: 'Fittings & Pipe',
    quantityOnHand: 4, // Below threshold of 10!
    minThreshold: 10,
    unit: 'pcs',
    unitCost: 4.85,
    preferredSupplier: 'Ferguson Plumbing Supply',
    reorderQty: 25,
    location: 'Van 1 & Van 2',
  },
  {
    id: 'stock-2',
    name: '1/2" PEX-A Expansion Ball Valve (Full Port)',
    sku: 'UPONOR-LF4855050',
    category: 'Valves',
    quantityOnHand: 3, // Below threshold of 6!
    minThreshold: 6,
    unit: 'pcs',
    unitCost: 12.40,
    preferredSupplier: 'Ferguson Plumbing Supply',
    reorderQty: 12,
    location: 'Van 1',
  },
  {
    id: 'stock-3',
    name: 'R-410A Refrigerant 25 lb Cylinder',
    sku: 'CHEMOURS-R410A',
    category: 'HVAC Gases',
    quantityOnHand: 1, // Below threshold of 2!
    minThreshold: 2,
    unit: 'tank',
    unitCost: 220.00,
    preferredSupplier: 'Johnstone Supply',
    reorderQty: 4,
    location: 'Shop Cage',
  },
  {
    id: 'stock-4',
    name: 'Square D QO 20-Amp Single-Pole Breaker',
    sku: 'SQD-QO120',
    category: 'Electrical',
    quantityOnHand: 18,
    minThreshold: 8,
    unit: 'pcs',
    unitCost: 9.75,
    preferredSupplier: 'Graybar Electric',
    reorderQty: 10,
    location: 'Van 2',
  },
  {
    id: 'stock-5',
    name: 'Oatey Heavy Duty Clear PVC Cement (16 oz)',
    sku: 'OATEY-30863',
    category: 'Chemicals & Glues',
    quantityOnHand: 6,
    minThreshold: 4,
    unit: 'can',
    unitCost: 14.50,
    preferredSupplier: 'Home Depot Pro',
    reorderQty: 6,
    location: 'All Trucks',
  },
];

export const DEFAULT_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    assetType: 'vehicle',
    assetId: 'veh-1',
    assetName: 'Service Truck 1 (Ford F-250)',
    serviceType: 'Synthetic Oil & Filter Change + Tire Rotation',
    cost: 165.50,
    performedBy: 'Maplewood Ford Commercial Service',
    performedAt: '2026-05-10',
    mileageAtService: 20000,
    nextDueAt: '2026-11-10',
    notes: 'Brake pads measured at 7mm front, 8mm rear.',
  },
  {
    id: 'maint-2',
    assetType: 'tool',
    assetId: 'tool-1',
    assetName: 'RIDGID RP 351 ProPress Press Tool',
    serviceType: 'Annual 32,000-Cycle Factory Recalibration',
    cost: 280.00,
    performedBy: 'RIDGID Authorized Service Center',
    performedAt: '2026-01-15',
    nextDueAt: '2027-01-15',
    notes: 'Passed high-pressure crimp tolerance test with certification stamp.',
  },
];
