import type { EmailThemeId } from '@/emails/brand';

export type PlatformCampaignTemplate = {
  id: string;
  name: string;
  category: 'announcement' | 'education' | 'promotion' | 'advisory' | 'blank';
  description: string;
  subject: string;
  preheader: string;
  eyebrow: string;
  heading: string;
  body: string;
  ctaLabel: string;
  ctaUrl: string;
  theme: EmailThemeId;
  defaultSenderName: string;
};

export const PLATFORM_CAMPAIGN_TEMPLATES: PlatformCampaignTemplate[] = [
  {
    id: 'welcome-quickstart',
    name: 'Welcome & Quick Start Guide',
    category: 'education',
    description: 'Provide newly registered contractors with an instant overview of their live website, quotes, and payouts.',
    subject: "🎉 Welcome to Let's Get Quoted — your website is live!",
    preheader: 'Here is your quick-start checklist to booking your first job.',
    eyebrow: 'Welcome Guide',
    heading: 'Welcome to Let’s Get Quoted, {{business_name}}!',
    body: `Hi {{first_name}},\n\nCongratulations on launching {{business_name}} on Let's Get Quoted! Your high-converting website has been created and is ready to take customer estimate requests.\n\n[STAT: 3 Min | Setup | Complete these 3 quick steps to book your first job this week.]\n\n## Your 3-Step Quick Start Checklist:\n\n1. Preview & Customize Your Website: Your trade services, service area, and Google SEO tags are already filled in. Add your company photos and logo in your dashboard.\n2. Build Your First 60-Second Quote: Test our fast quote builder with Good / Better / Best pricing tiers and instant one-click customer signatures.\n3. Connect Stripe for Next-Day Payouts: Link your bank account in 2 minutes so customers can pay deposits and invoices directly from their phone.\n\nTip: Contractors who link Stripe on Day 1 collect customer deposits 4x faster and eliminate payment delays.\n\nIf you ever need help configuring your trade presets or setting up your team, hit reply directly to this email — our team is here for you.`,
    ctaLabel: 'Open your dashboard & get started',
    ctaUrl: 'https://letsgetquoted.com/dashboard',
    theme: 'spotlight',
    defaultSenderName: "Let's Get Quoted Team",
  },
  {
    id: 'first-quote-closing',
    name: 'Closing Quotes Fast (Speed to Lead)',
    category: 'education',
    description: 'Teach contractors how sending interactive quotes with Good/Better/Best tiers closes 30% more jobs.',
    subject: 'How top contractors close 30% more jobs (in 2 minutes)',
    preheader: 'Send professional estimates that homeowners can approve from their phone.',
    eyebrow: 'Speed to Lead',
    heading: 'Win more high-margin estimates in less time',
    body: `Hi {{first_name}},\n\nDid you know that quotes sent within 2 hours of a site visit are 2.8x more likely to be approved on the spot?\n\n[STAT: 2.8x | Win Rate | Quotes sent within 2 hours of a site visit are 2.8x more likely to be approved on the spot.]\n\nHomeowners don't want to wait days for a PDF attachment in an email. With Let's Get Quoted, you can send an interactive estimate via SMS and email before you even leave their driveway:\n\n## 3 Ways to Close More Estimates:\n\n• Good / Better / Best Tiers: Give customers options to increase average invoice size by 22% without awkward upselling.\n• One-Click Mobile E-Signatures: Homeowners approve terms and sign right from their mobile browser with zero logins required.\n• Automated Reminders: Our system gently reminds undecided homeowners so quotes don't go cold.\n\nTip: Send your quote before leaving the customer's driveway for maximum approval rates.\n\nTry creating your first test estimate today and see how seamless the customer experience feels.`,
    ctaLabel: 'Create an estimate now',
    ctaUrl: 'https://letsgetquoted.com/dashboard/jobs/new',
    theme: 'blueprint',
    defaultSenderName: "Let's Get Quoted Advisor",
  },
  {
    id: 'stripe-deposit-setup',
    name: 'Stripe Connect & Deposit Setup',
    category: 'education',
    description: 'Explain next-day bank payouts, credit card processing, and eliminating unpaid invoices with upfront deposits.',
    subject: 'Collect deposits & get paid next-day with zero chasing',
    preheader: 'Unlock credit card, Apple Pay, and ACH payments for your business.',
    eyebrow: 'Instant Payouts',
    heading: 'Stop chasing unpaid invoices forever',
    body: `Hi {{first_name}},\n\nOne of the biggest headaches for trade businesses is waiting 30+ days for customer checks or driving across town to collect payment.\n\n[STAT: $0 | Chased Checks | Collect upfront card deposits automatically when quotes are approved.]\n\nBy connecting your Stripe account in Let's Get Quoted, you unlock complete payment automation:\n\n## Complete Payment Automation for {{business_name}}:\n\n• Automated Upfront Deposits: Collect a 25–50% card deposit automatically when the homeowner approves the quote before you schedule the work.\n• Instant Apple Pay & Card Processing: Customers pay in seconds from any smartphone via Card, Apple Pay, or Bank ACH.\n• Automatic Next-Day Payouts: Funds transfer directly into your business bank account with automated fee reconciliation.\n• Branded PDF Receipts: Instant, clean tax receipts sent to your client as soon as a payment clears.\n\nImportant: Setup takes less than 3 minutes through Stripe Connect. Link your account today to activate card processing.`,
    ctaLabel: 'Set up instant payouts',
    ctaUrl: 'https://letsgetquoted.com/dashboard/settings?tab=payouts',
    theme: 'studio',
    defaultSenderName: "Let's Get Quoted Financial Ops",
  },
  {
    id: 'seasonal-surge',
    name: 'Seasonal Trade Surge Readiness',
    category: 'education',
    description: 'Help contractors capture maximum demand before peak spring or fall seasons with early-bird booking.',
    subject: 'Preparing {{business_name}} for the upcoming seasonal rush',
    preheader: 'How to lock in booked jobs weeks in advance and maximize crew revenue.',
    eyebrow: 'Seasonal Playbook',
    heading: 'Fill your calendar before the busy season begins',
    body: `Hi {{first_name}},\n\nAs seasonal weather shifts, homeowner demand for inspections, cleanups, repairs, and system tune-ups surges.\n\n[STAT: 3-4 Wks | In Advance | Top trade contractors fill their peak seasonal calendar a month ahead of time.]\n\nThe most profitable contractors don't wait for the phone to ring — they fill their calendar 3 to 4 weeks ahead of time using three simple steps:\n\n## Your 3-Step Seasonal Surge Playbook:\n\n1. Send an Early-Bird Maintenance Invite: Broadcast a seasonal service offer to past clients via SMS and email.\n2. Enable Online Self-Booking: Let homeowners claim inspection slots directly from your website.\n3. Group Jobs by Neighborhood: Cluster nearby jobs on the calendar to cut crew drive time in half.\n\nTip: Launch your campaign before the first cold snap or heat wave to capture homeowners while search volume spikes.\n\nYou can launch your seasonal outreach directly inside your Marketing tab in under 5 minutes.`,
    ctaLabel: 'Launch seasonal campaign',
    ctaUrl: 'https://letsgetquoted.com/dashboard/marketing',
    theme: 'spotlight',
    defaultSenderName: "Let's Get Quoted Advisor",
  },
  {
    id: 'google-reviews-flywheel',
    name: 'Automated 5-Star Google Reviews',
    category: 'education',
    description: 'Show contractors how automated post-job review texts build local trust and search rank on Google.',
    subject: 'How to turn every completed job into a 5-star Google review',
    preheader: 'Automate customer review requests and protect your reputation.',
    eyebrow: 'Reputation Flywheel',
    heading: 'Build an unbeatable 5-star Google rating on autopilot',
    body: `Hi {{first_name}},\n\n92% of homeowners check Google reviews before hiring a contractor. But asking for reviews in person is uncomfortable and easily forgotten when wrapping up a job.\n\n[STAT: 92% | Trust Factor | Homeowners check Google reviews before hiring a contractor in their area.]\n\nWith Let's Get Quoted, you never have to ask manually:\n\n## How Your Automated Review Flywheel Works:\n\n• Automated Review Requests: As soon as a job is marked complete or paid, our system sends a friendly text with your direct Google review link.\n• Private Feedback Route: If a customer had an issue, they are guided to a private resolution form instead of posting a negative public review.\n• Local SEO Surge: More recent 5-star reviews push your business to the top of Google Maps in your target service area.\n\nTip: Adding just five new 5-star reviews this month significantly boosts your ranking on Google Maps local search.\n\nConnect your Google Business Profile link in Settings to turn on review automation today.`,
    ctaLabel: 'Enable automated reviews',
    ctaUrl: 'https://letsgetquoted.com/dashboard/reviews',
    theme: 'neighborly',
    defaultSenderName: "Let's Get Quoted Growth Team",
  },
  {
    id: 'ai-voice-intake',
    name: 'AI Voice Intake: 24/7 Call Answering',
    category: 'announcement',
    description: 'Announce 24/7 AI call answering so contractors never lose an emergency lead to voicemail.',
    subject: 'Never lose another job to voicemail: Meet AI Voice Intake',
    preheader: '24/7 intelligent call answering that turns missed calls into quotes.',
    eyebrow: 'New Capability',
    heading: 'Answer every customer call 24/7 with AI Voice Intake',
    body: `Hi {{first_name}},\n\nWhen you are on a roof, under a sink, or running power tools, picking up the phone is nearly impossible. But 80% of homeowners who reach a voicemail simply hang up and call the next contractor on Google.\n\n[STAT: 24/7 | Live Intake | Never lose an emergency trade lead or after-hours call to voicemail again.]\n\nWith AI Voice Intake on Let's Get Quoted, you never lose a job to voicemail again:\n\n## What AI Voice Intake Does For {{business_name}}:\n\n• Natural 24/7 Call Answering: Our trained AI voice assistant answers after-hours and overflow calls using your business name.\n• Structured Job Details: It captures the caller’s address, requested service, urgency, and contact info.\n• Instant Quote Draft: All call transcripts and recordings land in your dashboard instantly drafted as a new estimate ready for your review.\n\nNote: Forward your existing business phone number or activate a new dedicated local line with 1 click in your workspace.`,
    ctaLabel: 'Try AI Voice Intake',
    ctaUrl: 'https://letsgetquoted.com/dashboard/settings?tab=voice',
    theme: 'spotlight',
    defaultSenderName: "Let's Get Quoted Product Team",
  },
  {
    id: 'quick-stops-revenue',
    name: 'Quick Stops: Monetize Route Gaps',
    category: 'education',
    description: 'Explain how Quick Stops lets contractors fill schedule gaps with high-margin rapid repair visits.',
    subject: 'Turn route gaps and cancellations into $1,200+ extra weekly',
    preheader: 'How to monetize empty calendar slots with high-margin Quick Stop jobs.',
    eyebrow: 'Efficiency Playbook',
    heading: 'Fill route gaps with profitable Quick Stop visits',
    body: `Hi {{first_name}},\n\nWhen a job wraps up early or a customer reschedules, your crew ends up sitting in traffic or waiting around.\n\n[STAT: +$1,200 | Weekly Revenue | Turn schedule gaps and early job completions into high-margin repair visits.]\n\nQuick Stops on Let's Get Quoted turns those empty slots into instant revenue:\n\n## How Quick Stops Monetizes Route Gaps:\n\n• Instant Small Repairs: Offer predefined 30–60 minute repair packages (e.g. minor leaks, diagnostic checks, gutter clears, switch replacements).\n• Same-Day Dispatch: Homeowners request quick help with upfront flat pricing; you accept when it fits your crew’s route.\n• Zero Quoting Friction: Payment is authorized upfront before arrival so you never waste time quoting small fixes.\n\nTip: Activate Quick Stops whenever your crew finishes a morning job 45 minutes ahead of schedule.\n\nCheck out the Quick Stops tab in your dashboard to activate nearby requests.`,
    ctaLabel: 'Explore Quick Stops',
    ctaUrl: 'https://letsgetquoted.com/dashboard/quick-stops',
    theme: 'blueprint',
    defaultSenderName: "Let's Get Quoted Advisor",
  },
  {
    id: 'feature-launch',
    name: 'New Feature Launch',
    category: 'announcement',
    description: 'Announce major product updates, new tools, and workflow improvements to all contractors.',
    subject: "New on Let's Get Quoted: Instant Client Approvals & Live Tracking",
    preheader: 'See what is new in your dashboard today to win more jobs faster.',
    eyebrow: 'Product Update',
    heading: 'Exciting new features are now live in your account',
    body: `Hi {{first_name}},\n\nWe have just released a series of updates designed to help {{business_name}} close jobs faster and save hours on administration each week.\n\n[STAT: New | Updates Live | Explore the latest workflow enhancements built to save you hours each week.]\n\n## What is New in Your Workspace:\n\n• One-Click Quote Approvals: Homeowners can now approve and sign estimates directly from their phone in seconds.\n• Live Arrival Tracking: Automated SMS notifications let your customers see when your crew is on their way.\n• Instant Payment Receipts: Clean, branded PDFs automatically delivered when deposits and invoices are cleared.\n\nNote: These updates are already available in your workspace — no setup required.`,
    ctaLabel: 'Open your dashboard & explore',
    ctaUrl: 'https://letsgetquoted.com/dashboard',
    theme: 'spotlight',
    defaultSenderName: "Let's Get Quoted Product Team",
  },
  {
    id: 'founder-letter',
    name: 'Founder Letter / Roadmap',
    category: 'announcement',
    description: 'A personal note from founder Brett regarding the roadmap, contractor stories, and tips.',
    subject: "A quick update on where we're headed (and what's next for your trade)",
    preheader: "Behind the scenes at Let's Get Quoted and what we are building for you.",
    eyebrow: 'From the Founder',
    heading: 'Building the fastest software for trade businesses',
    body: `Hi {{first_name}},\n\nI wanted to share a quick personal note to thank you for building your business with Let's Get Quoted.\n\n> "Our single mission at Let's Get Quoted is to build the fastest, most reliable software for independent trade contractors."\n\nOver the past quarter, we have listened closely to feedback from hundreds of trade contractors across roofing, plumbing, HVAC, electrical, and general contracting. Your insights have directly shaped our upcoming roadmap:\n\n## What We Are Building Next for Your Trade:\n\n1. Smarter Scheduling: Intelligent calendar route planning to cut drive time between jobs.\n2. AI Voice Intake: Automated 24/7 call answering that turns missed calls into structured estimate requests.\n3. Deeper Accounting Sync: Seamless two-way integration with QuickBooks Online.\n\nTip: Have a feature request or workflow challenge? Hit reply to this email to share your thoughts directly with our product team. I read every response.`,
    ctaLabel: 'View your business overview',
    ctaUrl: 'https://letsgetquoted.com/dashboard',
    theme: 'studio',
    defaultSenderName: "Brett at Let's Get Quoted",
  },
  {
    id: 'growth-playbook',
    name: 'Contractor Growth Playbook',
    category: 'education',
    description: 'Share actionable tips, pricing strategies, and best practices to help contractors grow.',
    subject: '3 ways top contractors are increasing quote conversion by 30%',
    preheader: 'Actionable tips from top-performing trades on our platform.',
    eyebrow: 'Growth Playbook',
    heading: 'How to win more high-margin jobs this season',
    body: `Hi {{first_name}},\n\nWhen we analyzed the contractors with the highest win rates on Let's Get Quoted, three clear patterns stood out:\n\n[STAT: +30% | Conversion | Three proven strategies used by top-performing trade businesses on our platform.]\n\n## The High-Conversion Quoting Framework:\n\n1. Send the quote within 2 hours: Quotes sent within 120 minutes of a site visit are 2.8x more likely to be approved on the spot.\n2. Provide good-better-best options: Offering an upgraded tier increases average job value by 22% without adding sales pressure.\n3. Request deposits upfront: Locking in 25-50% deposit before scheduling reduces cancellations to near zero.\n\nPro Tip: Pre-save standard pricing packages in your settings to draft custom multi-tier estimates in under 60 seconds.`,
    ctaLabel: 'Create a quote now',
    ctaUrl: 'https://letsgetquoted.com/dashboard/jobs/new',
    theme: 'blueprint',
    defaultSenderName: "Let's Get Quoted Advisor",
  },
  {
    id: 'upgrade-promotion',
    name: 'Special Promotion / Plan Upgrade',
    category: 'promotion',
    description: 'Incentivize free and trial users to upgrade with feature highlights and special offers.',
    subject: 'Unlock unlimited estimates, crew seats, and custom branding',
    preheader: 'Upgrade your workspace to scale your business with zero limits.',
    eyebrow: 'Special Offer',
    heading: 'Upgrade {{business_name}} to unlock full platform power',
    body: `Hi {{first_name}},\n\nReady to take {{business_name}} to the next level? Upgrading to a paid plan unlocks everything you need to run high-volume operations smoothly:\n\n[STAT: Unlimited | Scale Ready | Remove limits on quotes, custom website branding, crew seats, and dispatch.]\n\n## Everything Included in Your Upgraded Plan:\n\n• Unlimited quotes and invoices every month with zero overage fees\n• Custom website builder hosted on your own branded domain\n• Team & crew access with dedicated field dispatch and arrival alerts\n• Automated customer review generation and Google Business sync\n\nNote: Upgrade today to lock in your premier founder tier pricing for the lifetime of your account.`,
    ctaLabel: 'Explore upgrade plans',
    ctaUrl: 'https://letsgetquoted.com/dashboard/billing',
    theme: 'spotlight',
    defaultSenderName: "Let's Get Quoted",
  },
  {
    id: 'service-advisory',
    name: 'Service Advisory & System Notice',
    category: 'advisory',
    description: 'Important updates regarding tax rules, carrier regulations, maintenance, or security.',
    subject: 'Important advisory: Carrier messaging compliance & account updates',
    preheader: 'Please review these important compliance requirements for your business.',
    eyebrow: 'Operational Notice',
    heading: 'Important system and compliance information for your account',
    body: `Hello {{first_name}},\n\nWe are sharing an important update regarding regulatory messaging guidelines and system security best practices for trade contractors.\n\nImportant: Carrier messaging regulations require all trade businesses to maintain verified business profiles.\n\nAll automated SMS reminders, customer arrival alerts, and quote notifications sent through Let's Get Quoted adhere strictly to US telecom 10DLC compliance standards.\n\n## Action Needed for {{business_name}}:\n\n• Verify Legal Business Name: Ensure the name on your account matches your legal entity or registration.\n• Confirm Contact Phone & Address: Update your physical address and primary contact phone in settings.\n• Keep Customer Opt-Ins Active: Maintain standard customer consent for automated arrival alerts and quote updates.\n\nNote: Keeping your profile up to date guarantees 100% carrier delivery rates for all client SMS alerts.`,
    ctaLabel: 'Review account settings',
    ctaUrl: 'https://letsgetquoted.com/dashboard/settings',
    theme: 'letterhead',
    defaultSenderName: "Let's Get Quoted Support",
  },
  {
    id: 'blank',
    name: 'Start from Scratch',
    category: 'blank',
    description: 'A clean slate to write your custom broadcast or announcement.',
    subject: 'Announcement for {{business_name}}',
    preheader: 'Important update from Let’s Get Quoted.',
    eyebrow: 'Announcement',
    heading: 'Update from Let’s Get Quoted',
    body: `Hi {{first_name}},\n\nWe are writing to share an update regarding {{business_name}} and your Let's Get Quoted workspace.\n\nPlease feel free to reply directly to this email if you have any questions.`,
    ctaLabel: 'Visit dashboard',
    ctaUrl: 'https://letsgetquoted.com/dashboard',
    theme: 'studio',
    defaultSenderName: "Let's Get Quoted",
  },
];
