/**
 * Plain punctuation for labels generated by the system, such as time windows.
 * Apply before combining with names or freeform text; this is not a transport
 * sanitizer. All other characters, including meaningful non-English text, stay.
 */
export function normalizeSmsSystemText(text: string): string {
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\u2026/g, '...')
    .replace(/[\u00a0\u202f]/g, ' ');
}
