export interface StoreProductCatalogItem {
  id: string;
  retailer: 'Home Depot' | "Lowe's";
  name: string;
  brand: string;
  category: string;
  modelNumber: string;
  sku: string; // Internet # or Item #
  price: number;
  imageUrl: string;
  storeUrl: string;
  description: string;
  keywords: string[];
}

export const STORE_PRODUCTS_CATALOG: StoreProductCatalogItem[] = [
  // ── Pipe & Plumbing Tools ──────────────────────────────────────────────────
  {
    id: 'hd-pipe-1',
    retailer: 'Home Depot',
    name: 'RIDGID 18 in. Heavy-Duty Straight Pipe Wrench',
    brand: 'RIDGID',
    category: 'Hand Tools',
    modelNumber: '31025',
    sku: '100072045',
    price: 49.97,
    imageUrl: '/images/tools/ridgid-pipe-wrench.jpg',
    storeUrl: 'https://www.homedepot.com/p/RIDGID-18-in-Heavy-Duty-Straight-Pipe-Wrench-31025/100072045',
    description: 'Iconic red ductile-iron housing with full floating forged hook jaw. Capacity up to 2-1/2 in. pipe.',
    keywords: ['pipe', 'wrench', 'ridgid', 'plumbing', 'steel', '18', 'hand tool', 'pipe wrench'],
  },
  {
    id: 'hd-pipe-2',
    retailer: 'Home Depot',
    name: 'RIDGID RP 351 ProPress Press Tool Kit with Jaws (1/2" - 2")',
    brand: 'RIDGID',
    category: 'Pipe Joining',
    modelNumber: 'RP 351',
    sku: '319409824',
    price: 3850.0,
    imageUrl: '/images/tools/ridgid-propress.jpg',
    storeUrl: 'https://www.homedepot.com/p/RIDGID-RP-351-ProPress-Press-Tool-Kit-with-1-2-in-to-2-in-ProPress-Jaws-67123/319409824',
    description: 'Next generation inline press tool delivering 7,200 lbs of hydraulic crimp force for copper and stainless pipe.',
    keywords: ['pipe', 'propress', 'press', 'ridgid', 'copper', 'plumbing', 'crimp', 'joining', 'rp351'],
  },
  {
    id: 'hd-pipe-3',
    retailer: 'Home Depot',
    name: 'Milwaukee M12 Cordless Copper Tubing / Pipe Cutter',
    brand: 'Milwaukee',
    category: 'Cutting Tools',
    modelNumber: '2471-20',
    sku: '202196535',
    price: 149.0,
    imageUrl: '/images/tools/milwaukee-bandsaw.jpg',
    storeUrl: 'https://www.homedepot.com/p/Milwaukee-M12-12-Volt-Lithium-Ion-Cordless-Copper-Tubing-Cutter-Tool-Only-2471-20/202196535',
    description: 'Cuts up to 10X faster than manual cutters. Self-adjusting mechanism cuts 3/8 in. to 1 in. copper tubing.',
    keywords: ['pipe', 'cutter', 'milwaukee', 'copper', 'tubing', 'm12', 'plumbing', 'cutting'],
  },
  {
    id: 'lowes-pipe-1',
    retailer: "Lowe's",
    name: 'DEWALT 20V MAX Cordless PEX / Pipe Expander Kit',
    brand: 'DEWALT',
    category: 'Pipe Joining',
    modelNumber: 'DCE400D2',
    sku: '1000579201',
    price: 499.0,
    imageUrl: '/images/tools/dewalt-drill.jpg',
    storeUrl: 'https://www.lowes.com/pd/DEWALT-20V-MAX-Cordless-PEX-Expander/1000579201',
    description: 'Auto-rotating head action expands 3/8-in to 1-in PEX pipe with onboard LED worklight.',
    keywords: ['pipe', 'pex', 'expander', 'dewalt', 'plumbing', 'water', '20v'],
  },
  {
    id: 'lowes-pipe-2',
    retailer: "Lowe's",
    name: 'Kobalt 14-in Heavy-Duty Cast Iron Pipe Wrench',
    brand: 'Kobalt',
    category: 'Hand Tools',
    modelNumber: '807387',
    sku: '807387',
    price: 24.98,
    imageUrl: '/images/tools/ridgid-pipe-wrench.jpg',
    storeUrl: 'https://www.lowes.com/pd/Kobalt-14-in-Steel-Pipe-Wrench/807387',
    description: 'Drop-forged jaw with induction hardened teeth for maximum grip on gas and water pipes.',
    keywords: ['pipe', 'wrench', 'kobalt', 'plumbing', 'steel', 'cast iron', 'hand tool'],
  },
  {
    id: 'hd-pipe-4',
    retailer: 'Home Depot',
    name: 'RIDGID Model 300 Compact 1/2 in. to 2 in. Pipe Threading Machine',
    brand: 'RIDGID',
    category: 'Pipe Joining',
    modelNumber: '300 Compact',
    sku: '202826772',
    price: 4690.0,
    imageUrl: '/images/tools/ridgid-propress.jpg',
    storeUrl: 'https://www.homedepot.com/p/RIDGID-300-Compact-1-2-in-to-2-in-Pipe-Threading-Machine-67182/202826772',
    description: 'Heavy-duty 1/2 hp electric motor with self-priming oil system for continuous pipe threading.',
    keywords: ['pipe', 'threader', 'threading', 'ridgid', 'commercial', 'iron', 'gas'],
  },

  // ── Saws & Cutting Tools ───────────────────────────────────────────────────
  {
    id: 'hd-saw-1',
    retailer: 'Home Depot',
    name: 'Milwaukee M18 FUEL Deep Cut Band Saw (Tool Only)',
    brand: 'Milwaukee',
    category: 'Cutting Tools',
    modelNumber: '2729-20',
    sku: '205629470',
    price: 349.0,
    imageUrl: '/images/tools/milwaukee-bandsaw.jpg',
    storeUrl: 'https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-Deep-Cut-Band-Saw-Tool-Only-2729-20/205629470',
    description: '5 in. by 5 in. cut capacity. POWERSTATE brushless motor with Jobsite Armor technology.',
    keywords: ['saw', 'bandsaw', 'band saw', 'milwaukee', 'deep cut', 'm18', 'fuel', 'cutting'],
  },
  {
    id: 'lowes-saw-1',
    retailer: "Lowe's",
    name: 'DEWALT 20V MAX Deep Cut Band Saw (Tool Only)',
    brand: 'DEWALT',
    category: 'Cutting Tools',
    modelNumber: 'DCS374B',
    sku: '1000002821',
    price: 329.0,
    imageUrl: '/images/tools/milwaukee-bandsaw.jpg',
    storeUrl: 'https://www.lowes.com/pd/DEWALT-20V-MAX-Deep-Cut-Band-Saw/1000002821',
    description: '5 in. cutting capacity with variable speed dial and integrated hang hook.',
    keywords: ['saw', 'bandsaw', 'band saw', 'dewalt', 'deep cut', '20v', 'cutting'],
  },
  {
    id: 'hd-saw-2',
    retailer: 'Home Depot',
    name: 'Milwaukee M18 FUEL SAWZALL Reciprocating Saw',
    brand: 'Milwaukee',
    category: 'Cutting Tools',
    modelNumber: '2821-20',
    sku: '312893892',
    price: 219.0,
    imageUrl: '/images/tools/generic-tool.jpg',
    storeUrl: 'https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-SAWZALL-Reciprocating-Saw-Tool-Only-2821-20/312893892',
    description: 'Delivers 3,000 SPM with 1-1/4 in. stroke length for fast demo and pipe cuts.',
    keywords: ['saw', 'sawzall', 'reciprocating', 'milwaukee', 'demo', 'cutting', 'm18'],
  },

  // ── Drills & Power Tools ───────────────────────────────────────────────────
  {
    id: 'lowes-drill-1',
    retailer: "Lowe's",
    name: 'DEWALT 20V MAX 1/2-in Brushless Cordless Drill Driver',
    brand: 'DEWALT',
    category: 'Power Tools',
    modelNumber: 'DCD777C2',
    sku: '1000135831',
    price: 159.0,
    imageUrl: '/images/tools/dewalt-drill.jpg',
    storeUrl: 'https://www.lowes.com/pd/DEWALT-20V-MAX-1-2-in-Brushless-Cordless-Drill-Driver/1000135831',
    description: 'High-performance brushless motor delivers 340 unit watts out with ergonomic comfort grip.',
    keywords: ['drill', 'dewalt', 'cordless', 'driver', '20v', 'power tools', 'brushless'],
  },
  {
    id: 'hd-drill-1',
    retailer: 'Home Depot',
    name: 'Milwaukee M18 FUEL 1/2-in Hammer Drill / Driver',
    brand: 'Milwaukee',
    category: 'Power Tools',
    modelNumber: '2904-20',
    sku: '320379991',
    price: 199.0,
    imageUrl: '/images/tools/generic-tool.jpg',
    storeUrl: 'https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-1-2-in-Hammer-Drill-Tool-Only-2904-20/320379991',
    description: 'Delivers up to 1,400 in-lbs of torque with AutoStop control mode for enhanced safety.',
    keywords: ['drill', 'hammer drill', 'milwaukee', 'm18', 'fuel', 'power tools', 'driver'],
  },
  {
    id: 'hd-drill-2',
    retailer: 'Home Depot',
    name: 'RIDGID 18V SubCompact Brushless 1/2-in Drill Driver',
    brand: 'RIDGID',
    category: 'Power Tools',
    modelNumber: 'R87012B',
    sku: '313391746',
    price: 139.0,
    imageUrl: '/images/tools/generic-tool.jpg',
    storeUrl: 'https://www.homedepot.com/p/RIDGID-18V-SubCompact-Brushless-Cordless-1-2-in-Drill-Driver-R87012B/313391746',
    description: '30% more compact and lightweight with brushless power and all-metal chuck.',
    keywords: ['drill', 'ridgid', 'subcompact', '18v', 'driver', 'power tools'],
  },
  {
    id: 'lowes-impact-1',
    retailer: "Lowe's",
    name: 'Kobalt 24V Max 1/2-in Brushless Cordless Impact Wrench',
    brand: 'Kobalt',
    category: 'Power Tools',
    modelNumber: 'KCS-24-03',
    sku: '5013098317',
    price: 199.0,
    imageUrl: '/images/tools/generic-tool.jpg',
    storeUrl: 'https://www.lowes.com/pd/Kobalt-24V-Max-1-2-in-Brushless-Cordless-Impact-Wrench/5013098317',
    description: 'Delivers 650 ft-lbs of breakaway torque with 3-speed selector and electronic finish mode.',
    keywords: ['impact', 'wrench', 'kobalt', '24v', 'power tools', 'impact wrench', 'automotive'],
  },

  // ── Diagnostics & Electrical ───────────────────────────────────────────────
  {
    id: 'hd-elec-1',
    retailer: 'Home Depot',
    name: 'Klein Tools MM400 Auto-Ranging Digital Multimeter 600V',
    brand: 'Klein Tools',
    category: 'Diagnostics',
    modelNumber: 'MM400',
    sku: '206517333',
    price: 59.97,
    imageUrl: '/images/tools/klein-multimeter.jpg',
    storeUrl: 'https://www.homedepot.com/p/Klein-Tools-Digital-Multimeter-600V-Auto-Ranging-MM400/206517333',
    description: 'Measures up to 600V AC/DC voltage, 10A AC/DC current, resistance, temperature, and continuity.',
    keywords: ['multimeter', 'klein', 'tester', 'electrical', 'voltage', 'diagnostics', 'meter'],
  },
  {
    id: 'hd-elec-2',
    retailer: 'Home Depot',
    name: 'Klein Tools CL800 600A Digital AC/DC TRMS Clamp Meter',
    brand: 'Klein Tools',
    category: 'Diagnostics',
    modelNumber: 'CL800',
    sku: '206517428',
    price: 149.97,
    imageUrl: '/images/tools/klein-multimeter.jpg',
    storeUrl: 'https://www.homedepot.com/p/Klein-Tools-600-Amp-Digital-Clamp-Meter-CL800/206517428',
    description: 'True RMS AC/DC clamp meter with Low Impedance (LoZ) mode to eliminate ghost voltages.',
    keywords: ['clamp meter', 'klein', 'amperage', 'electrical', 'diagnostics', 'meter', 'trms'],
  },
  {
    id: 'hd-diag-1',
    retailer: 'Home Depot',
    name: 'FLIR E8-XT Infrared Thermal Camera with MSX',
    brand: 'FLIR',
    category: 'Diagnostics',
    modelNumber: 'E8-XT',
    sku: '312389104',
    price: 2995.0,
    imageUrl: '/images/tools/flir-thermal.jpg',
    storeUrl: 'https://www.homedepot.com/p/FLIR-E8-XT-Infrared-Thermal-Camera/312389104',
    description: 'High-resolution 320x240 thermal detector with MSX image enhancement for pipe leaks and electrical hot spots.',
    keywords: ['thermal', 'camera', 'flir', 'infrared', 'diagnostics', 'leak', 'heat', 'inspection'],
  },

  // ── HVAC Diagnostics ───────────────────────────────────────────────────────
  {
    id: 'hd-hvac-1',
    retailer: 'Home Depot',
    name: 'Fieldpiece SMAN480V 4-Port Wireless Digital Manifold with Micron Gauge',
    brand: 'Fieldpiece',
    category: 'HVAC Diagnostics',
    modelNumber: 'SMAN480V',
    sku: '314902188',
    price: 795.0,
    imageUrl: '/images/tools/fieldpiece-manifold.jpg',
    storeUrl: 'https://www.homedepot.com/p/Fieldpiece-SMAN480V-4-Port-Wireless-Manifold/314902188',
    description: 'Heavy-duty 4-valve manifold with wireless pipe clamps and real-time superheat/subcooling calculations.',
    keywords: ['manifold', 'fieldpiece', 'hvac', 'gauges', 'refrigerant', 'freon', 'diagnostics'],
  },

  // ── Drain Cleaning & Jetters ───────────────────────────────────────────────
  {
    id: 'hd-drain-1',
    retailer: 'Home Depot',
    name: 'Spartan 738 Commercial Water Jetter 3000 PSI',
    brand: 'Spartan Tool',
    category: 'Drain Cleaning',
    modelNumber: 'Model 738',
    sku: '301902144',
    price: 8200.0,
    imageUrl: '/images/tools/spartan-jetter.jpg',
    storeUrl: 'https://www.homedepot.com/p/Spartan-738-Commercial-Water-Jetter-3000-PSI/301902144',
    description: 'Gas-powered 3,000 PSI at 4 GPM sewer jetter on portable powder-coated cart with 250 ft hose reel.',
    keywords: ['jetter', 'drain', 'spartan', 'hydrojetter', 'sewer', 'cleaning', 'plumbing', 'high pressure'],
  },
  {
    id: 'hd-drain-2',
    retailer: 'Home Depot',
    name: 'RIDGID K-400 Drum Machine with 75 ft. Cable',
    brand: 'RIDGID',
    category: 'Drain Cleaning',
    modelNumber: 'K-400',
    sku: '202826764',
    price: 1150.0,
    imageUrl: '/images/tools/spartan-jetter.jpg',
    storeUrl: 'https://www.homedepot.com/p/RIDGID-K-400-Drum-Machine-with-75-ft-Cable-26993/202826764',
    description: 'Reliable 1-1/2 in. to 4 in. drain line cleaner with integrated transport cart and cable guide.',
    keywords: ['drain', 'auger', 'snake', 'ridgid', 'k400', 'sewer', 'drum machine', 'cleaning'],
  },
];
