import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = process.cwd();
const START = '-- BEGIN GENERATED SIGNALWIRE MESSAGING AND VOICE RUNTIME';
const END = '-- END GENERATED SIGNALWIRE MESSAGING AND VOICE RUNTIME';
const MIGRATIONS = [
  'migrations/2026-08-03-reschedule-offers.sql',
  'migrations/2026-08-17-subcontractor-dispatch.sql',
  'migrations/20260815213142_pricing_entitlements.sql',
  'migrations/20260815220739_pricing_entitlements_hardening.sql',
  'migrations/20260816061500_paid_plan_monthly_allowance_reset.sql',
  'migrations/20260816083000_direct_payment_settlement_foundation.sql',
  'migrations/20260818190000_top_up_purchase_operations.sql',
  'migrations/20260818210000_workspace_purchased_capacity.sql',
  'migrations/20260819080000_usage_overage_authorization.sql',
  'migrations/20260819100000_webhook_source_ai_voice.sql',
  'migrations/20260819110000_commit_usage_reservation_partial.sql',
  'migrations/20260819120000_voice_event_inbox.sql',
  'migrations/20260819130000_lead_source_ai_voice.sql',
  'migrations/20260819140000_voice_settings.sql',
  'migrations/20260819150000_voice_calls.sql',
  'migrations/20260819160000_voice_settings_truncate.sql',
  'migrations/20260819170000_revoke_truncate_from_browser_roles.sql',
  'migrations/20260819180000_top_up_ledger_voice_skus.sql',
  'migrations/20260819190000_voice_minute_allowance.sql',
  'migrations/20260819200000_assert_canonical_reset_untouched.sql',
  'migrations/20260819260000_overage_settlement.sql',
  'migrations/20260819290000_overage_accrual_idempotency.sql',
  'migrations/20260819300000_release_respects_settled_period.sql',
  'migrations/20260819310000_cap_counts_overlapping_periods.sql',
  'migrations/20260820110000_voice_allowance_survives_a_moved_period.sql',
  'migrations/20260820120000_settle_a_voice_overage_for_what_was_used.sql',
  'migrations/20260821180506_sms_delivery_foundation.sql',
  'migrations/20260821182355_sms_webhook_safety.sql',
  'migrations/20260821182357_signalwire_dedicated_number_provisioning.sql',
  'migrations/20260821190000_voice_runtime_hardening.sql',
  'migrations/20260821191000_voice_admission_concurrency.sql',
  'migrations/20260821191500_sms_usage_finalization.sql',
  'migrations/20260821191700_sms_status_auto_reconciliation.sql',
  'migrations/20260821192000_sms_inbound_action_outbox.sql',
  'migrations/20260821194000_producer_sms_queue_projection.sql',
  'migrations/20260821195147_signalwire_dedicated_number_hardening.sql',
  'migrations/20260821204404_signalwire_dedicated_number_adversarial_hardening.sql',
  'migrations/20260821210000_sms_durability_followups.sql',
  'migrations/20260821210500_sms_purpose_aware_inbound_routing.sql',
  'migrations/20260821221223_voice_dedicated_number_invariant.sql',
  'migrations/20260821230000_voice_transcript_retention.sql',
] as const;

function lf(value: string): string {
  return value.replace(/\r\n/g, '\n');
}

function digest(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

describe('fresh-environment messaging schema parity', () => {
  it('mirrors the complete ordered runtime migrations into schema.sql', () => {
    const schema = lf(readFileSync(join(ROOT, 'schema.sql'), 'utf8'));
    const start = schema.indexOf(START);
    const end = schema.indexOf(END, start);
    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);

    const actual = schema.slice(start, end + END.length);
    const sections = MIGRATIONS.map((migration) => {
      const body = lf(readFileSync(join(ROOT, migration), 'utf8')).trim();
      return `-- Source: ${migration}\n${body}`;
    });
    const expected = `${START}\n-- Generated by scripts/sync-messaging-schema.mjs. Do not edit this block by hand.\n\n${sections.join('\n\n')}\n${END}`;

    expect(digest(actual), 'Run node scripts/sync-messaging-schema.mjs --write').toBe(digest(expected));
  });
});
