GRANT SELECT (parcel_number) ON public.jobs TO authenticated;

CREATE OR REPLACE VIEW public.job_access AS
 SELECT j.id,
    j.account_id,
    j.ref,
    j.client_name,
    j.client_phone,
    j.address,
    j.scope,
    j.status,
    j.lead_source,
    j.scheduled_for,
    j.certificate,
    j.created_at,
    (COALESCE(q.quoted_amount, (0)::numeric))::numeric(12,2) AS quoted_amount,
    j.photo_paths,
    j.scheduled_time,
    j.estimated_hours,
    j.client_email,
    q.quote_items,
    j.client_id,
    j.appointment_confirmed_at,
    q.deposit_gate,
    j.lat,
    j.lng,
    j.geocoded_at,
    j.scheduled_until,
    j.recurring_plan_id,
    j.recurring_visit_date,
    j.started_at,
    j.booking_requested_date,
    j.booking_requested_time,
    j.booking_confirmed_at,
    j.booking_declined_at,
    q.reschedule_discount_percent,
    q.reschedule_discount_note,
    q.reschedule_discount_agreed_at,
    j.arrival_confirm_sent_at,
    j.booking_requested_end_time,
    j.booking_note,
    j.weather_sensitive,
    j.message_channel,
    j.booking_alt_date,
    j.booking_alt_time,
    j.booking_alt_end_time,
    q.quote_signer_name,
    q.quote_signed_at,
    q.quote_signature_path,
    q.quote_signature_method,
    j.test_marker,
    j.deleted_at,
    j.purge_after,
    j.deleted_by_user_id,
    j.deletion_reason,
    j.delete_operation_id,
    j.source_voice_provider_call_id,
    j.room_spatial_scan,
    j.document_email_revision,
    j.parcel_number
   FROM (jobs j
     LEFT JOIN LATERAL jsonb_populate_record(NULL::jobs, private.job_quote_values(j.id)) q(id, account_id, ref, client_name, client_phone, address, scope, status, lead_source, scheduled_for, certificate, created_at, quoted_amount, photo_paths, scheduled_time, estimated_hours, client_email, quote_items, client_id, appointment_confirmed_at, deposit_gate, lat, lng, geocoded_at, scheduled_until, recurring_plan_id, recurring_visit_date, started_at, booking_requested_date, booking_requested_time, booking_confirmed_at, booking_declined_at, reschedule_discount_percent, reschedule_discount_note, reschedule_discount_agreed_at, arrival_confirm_sent_at, booking_requested_end_time, booking_note, weather_sensitive, message_channel, booking_alt_date, booking_alt_time, booking_alt_end_time, quote_signer_name, quote_signed_at, quote_signature_path, quote_signature_method, test_marker, deleted_at, purge_after, deleted_by_user_id, deletion_reason, delete_operation_id, source_voice_provider_call_id, room_spatial_scan, document_email_revision, parcel_number) ON (true));
