import Link from 'next/link';
import type { Metadata } from 'next';
import SaveButton from '@/components/save-button';
import { ALREADY_CLAIMED_MESSAGE, SELECTION_MODE_LABEL, expiryLabel } from '@/lib/subcontractor-dispatch';
import { loadPublicOffer } from '@/lib/subcontractor-dispatch-data';
import { FieldInspectionChecklist } from '@/components/permits/FieldInspectionChecklist';
import { acceptOfferAction, askQuestionAction, declineOfferAction, keepAsBackupAction } from './actions';
import styles from './sub.module.css';

// The subcontractor's page. No account, no password, no app.
//
// WHAT IS AND IS NOT ON IT, because this is the page where getting that wrong
// costs a homeowner their privacy:
//
//   BEFORE ACCEPTANCE — the work, the area, the day, the money, the
//   requirements, the deadline. No street address, no customer name, no phone
//   number, no email. Those fields are not hidden here; loadPublicOffer never
//   puts them in the payload at all (see PublicOfferView.authorized), so there
//   is nothing on this page that a view-source could reveal.
//
//   AFTER ACCEPTANCE — the address and the contact, because the person who just
//   took the job has to drive there.
//
// One H1. The heading is the job before a decision and the outcome afterwards,
// because those are genuinely the two things this page is about at those two
// moments.

export const dynamic = 'force-dynamic';

/**
 * Never indexed, never previewed.
 *
 * A link in this family is a bearer credential. A crawler that follows one from
 * a forwarded email would mark the offer viewed, and a link preview generated by
 * a messaging app would put the job in a card in somebody's chat list.
 */
export const metadata: Metadata = {
  title: 'Subcontract job offer',
  robots: { index: false, follow: false, nocache: true },
};

function Missing() {
  return (
    <main className={styles.shell}>
      <div className={styles.outcome}>
        <h1>This job link is no longer available</h1>
        <p>
          It may have expired, been withdrawn, or already been filled. If you think it should still work, text the
          contractor who sent it.
        </p>
      </div>
    </main>
  );
}

export default async function SubcontractorOfferPage({ params: paramsPromise }: { params: Promise<{ token: string }> }) {
  const params = await paramsPromise;
  const page = await loadPublicOffer(params.token);
  if (!page) return <Missing />;

  const { view, outcome, alreadyBackup, questionAsked } = page;
  const expires = expiryLabel(view.expiresAt, new Date());

  // -- settled states ------------------------------------------------------
  // Each of these is a whole page rather than a banner over the offer: once the
  // decision is made or taken, the form underneath it is not something to
  // scroll past, it is something to remove.

  if (outcome.kind === 'accepted' && view.authorized) {
    return (
      <main className={styles.shell}>
        <header className={styles.brand}>
          <span className={styles.brandName}>{view.businessName}</span>
        </header>
        <div className={`${styles.outcome} ${styles.outcomeAccepted}`}>
          <h1>You&rsquo;ve got the job</h1>
          <p>
            {view.jobTitle} — {view.scheduleLabel || 'date to be confirmed'}. {view.payLabel} on completion.
          </p>
          <div className={styles.authorized}>
            <dl className={styles.facts}>
              <div className={styles.fact}>
                <dt>Address</dt>
                <dd>
                  {view.authorized.address ? (
                    <a
                      href={`https://maps.google.com/?q=${encodeURIComponent(view.authorized.address)}`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      {view.authorized.address}
                    </a>
                  ) : (
                    'The contractor will confirm the address.'
                  )}
                </dd>
              </div>
              <div className={styles.fact}>
                <dt>Customer</dt>
                <dd>
                  {view.authorized.clientName}
                  {view.authorized.clientPhone ? (
                    <>
                      {' · '}
                      <a href={`tel:${view.authorized.clientPhone}`}>{view.authorized.clientPhone}</a>
                    </>
                  ) : null}
                </dd>
              </div>
              {view.authorized.jobRef ? (
                <div className={styles.fact}>
                  <dt>Job reference</dt>
                  <dd>{view.authorized.jobRef}</dd>
                </div>
              ) : null}
            </dl>
          </div>
          <h2>What happens next</h2>
          <ol className={styles.nextSteps}>
            <li>{view.businessName} has been told you accepted, and every other offer has closed.</li>
            <li>Arrive inside the window above. Call the customer first if you are running late.</li>
            <li>Invoice {view.businessName} when the work is done — not the homeowner.</li>
          </ol>
          <FieldInspectionChecklist />
        </div>
        <p className={styles.footer}>
          Sent by {view.businessName} through Let&rsquo;s Get Quoted · <Link href="/privacy">Privacy</Link>
        </p>
      </main>
    );
  }

  if (outcome.kind === 'interested') {
    return (
      <main className={styles.shell}>
        <header className={styles.brand}>
          <span className={styles.brandName}>{view.businessName}</span>
        </header>
        <div className={`${styles.outcome} ${styles.outcomeAccepted}`}>
          <h1>You&rsquo;re on the list</h1>
          <p>
            {view.businessName} knows you can take the {view.jobTitle.toLowerCase()}. They are choosing between the
            firms who put their hand up and will be in touch — nothing is booked yet.
          </p>
        </div>
      </main>
    );
  }

  if (outcome.kind === 'claimed') {
    return (
      <main className={styles.shell}>
        <header className={styles.brand}>
          <span className={styles.brandName}>{view.businessName}</span>
        </header>
        <div className={`${styles.outcome} ${styles.outcomeClaimed}`}>
          <h1>{ALREADY_CLAIMED_MESSAGE}</h1>
          <p>
            Another subcontractor accepted it first. Nothing you did was wrong, and {view.businessName} will send you
            the next one.
          </p>
        </div>
        {alreadyBackup ? (
          <div className={styles.card}>
            <p className={styles.lede}>
              You are down as backup for this one. If the job comes free again, you hear about it first.
            </p>
          </div>
        ) : (
          <form action={keepAsBackupAction.bind(null, params.token)} className={styles.card}>
            <p className={styles.lede}>
              If the firm who took it falls through, do you want first refusal?
            </p>
            <div style={{ marginTop: '0.75rem' }}>
              <SaveButton className="btn secondary" pendingLabel="Saving…" savedLabel="Saved ✓">
                Keep me as backup
              </SaveButton>
            </div>
          </form>
        )}
      </main>
    );
  }

  if (outcome.kind === 'declined') {
    return (
      <main className={styles.shell}>
        <header className={styles.brand}>
          <span className={styles.brandName}>{view.businessName}</span>
        </header>
        <div className={styles.outcome}>
          <h1>Thanks for letting us know</h1>
          <p>
            {view.businessName} has been told you are not available for this one. {alreadyBackup ? 'You are down as backup if it comes free again.' : ''}
          </p>
        </div>
      </main>
    );
  }

  if (outcome.kind === 'expired' || outcome.kind === 'cancelled') {
    return (
      <main className={styles.shell}>
        <header className={styles.brand}>
          <span className={styles.brandName}>{view.businessName}</span>
        </header>
        <div className={styles.outcome}>
          <h1>{outcome.kind === 'expired' ? 'This offer has expired' : 'This offer was withdrawn'}</h1>
          <p>
            {outcome.kind === 'expired'
              ? `It closed at ${expires}. ${view.businessName} may reopen it — you will get a new link if they do.`
              : `${view.businessName} pulled the job. Nothing is needed from you.`}
          </p>
        </div>
      </main>
    );
  }

  // -- the live offer --------------------------------------------------------

  return (
    <main className={styles.shell}>
      <header className={styles.brand}>
        <div>
          <div className={styles.brandName}>{view.businessName}</div>
          <div className={styles.brandNote}>Subcontract job offer</div>
        </div>
      </header>

      <article className={styles.card}>
        <h1 className={styles.title}>{view.jobTitle}</h1>
        <p className={styles.lede}>
          {view.generalLocation}
          {view.distanceMiles !== null ? ` · about ${view.distanceMiles} miles from you` : ''}
        </p>

        <dl className={styles.facts}>
          <div className={styles.fact}>
            <dt>When</dt>
            <dd>{view.scheduleLabel || 'The contractor will confirm a date'}</dd>
          </div>
          <div className={styles.fact}>
            <dt>Pay</dt>
            <dd className={styles.pay}>
              <span className={styles.payAmount}>{view.payLabel}</span>
              <span className={styles.payKind}>
                {view.payKind === 'fixed' ? 'fixed price' : view.payKind === 'hourly' ? 'per hour' : 'per day'}
              </span>
            </dd>
          </div>
          <div className={styles.fact}>
            <dt>Scope</dt>
            <dd>{view.scope}</dd>
          </div>
          {view.requirements.length > 0 ? (
            <div className={styles.fact}>
              <dt>Requirements</dt>
              <dd>
                <ul className={styles.requirements}>
                  {view.requirements.map((requirement) => (
                    <li key={requirement} className={styles.requirement}>
                      {requirement}
                    </li>
                  ))}
                </ul>
              </dd>
            </div>
          ) : null}
          <div className={styles.fact}>
            <dt>Offer expires</dt>
            <dd>{expires}</dd>
          </div>
        </dl>

        <p className={styles.privacyNote}>
          The full address and the customer&rsquo;s contact details are shown once you accept.
        </p>
      </article>

      <div className={styles.notice} role="note">
        <span className={styles.noticeStrong}>
          {view.selectionMode === 'first_accept' ? 'First qualified acceptance wins.' : SELECTION_MODE_LABEL[view.selectionMode]}
        </span>
        <span>
          {view.selectionMode === 'first_accept'
            ? 'This offer went to several subcontractors at once. Whoever accepts first gets the job, and the rest close automatically.'
            : 'Several subcontractors were asked. Say you are available and the contractor will choose.'}
        </span>
      </div>

      {questionAsked ? (
        <div className={styles.card}>
          <p className={styles.lede}>
            You asked: “{questionAsked}” — {view.businessName} has it and will reply. You can still accept below in the
            meantime.
          </p>
        </div>
      ) : null}

      {/* Both non-committal actions are collapsed, and Accept is not: the whole
          page exists to make one decision easy and the other two possible. */}
      <details className={styles.disclosure}>
        <summary className={styles.disclosureSummary}>
          <span>Ask a question</span>
          <span aria-hidden="true">＋</span>
        </summary>
        <form action={askQuestionAction.bind(null, params.token)} className={styles.disclosureBody}>
          <label htmlFor="question">What do you need to know?</label>
          <textarea
            id="question"
            name="question"
            rows={3}
            required
            maxLength={500}
            placeholder="Is the old unit in a basement? Any parking restrictions?"
          />
          <SaveButton className="btn secondary" pendingLabel="Sending…" savedLabel="Sent ✓">
            Send question
          </SaveButton>
        </form>
      </details>

      <details className={styles.disclosure}>
        <summary className={styles.disclosureSummary}>
          <span>Not available</span>
          <span aria-hidden="true">＋</span>
        </summary>
        <form action={declineOfferAction.bind(null, params.token)} className={styles.disclosureBody}>
          <label htmlFor="reason">Anything you want to add? (optional)</label>
          <input id="reason" name="reason" maxLength={300} placeholder="Booked that morning, could do the afternoon" />
          <label className="checkbox-row" htmlFor="backup">
            <input id="backup" name="backup" type="checkbox" />
            <span>Keep me as backup if it comes free</span>
          </label>
          <SaveButton className="btn secondary" pendingLabel="Sending…" savedLabel="Sent ✓">
            I&rsquo;m not available
          </SaveButton>
        </form>
      </details>

      <div className={styles.actionBar}>
        <div className={styles.actionBarInner}>
          <form action={acceptOfferAction.bind(null, params.token)}>
            <SaveButton className={`btn primary ${styles.accept}`} pendingLabel="Accepting…" savedLabel="Accepted ✓">
              Accept this job
            </SaveButton>
          </form>
        </div>
      </div>

      <p className={styles.footer}>
        Sent by {view.businessName} through Let&rsquo;s Get Quoted · <Link href="/privacy">Privacy</Link> ·{' '}
        <Link href="/sms-terms">SMS terms</Link>
      </p>
    </main>
  );
}
