import Link from 'next/link';
import { formatMoney } from '@/lib/jobs';
import type { VoiceMetrics } from '@/lib/insights-metrics';

/**
 * Voice SKU ROI: demonstrates the tangible business value generated by the AI
 * receptionist / voice assistant add-on.
 */
export default function VoiceInsightsCard({
  voice,
  basePath = '/dashboard',
}: {
  voice: VoiceMetrics;
  basePath?: string;
}) {
  const { hasVoice, totalCalls, answeredCalls, missedCalls, leadsCreated, estimatedRevenue, totalMinutes } = voice;

  if (!hasVoice && totalCalls === 0) {
    return null; // Don't show voice card if account doesn't use the voice SKU
  }

  return (
    <section className="panel ins-card ins-voice-card">
      <p className="ins-card-head">
        <span className="ins-chip is-voice" aria-hidden="true">📞</span> AI phone assistant ROI
      </p>

      <div className="ins-figures" style={{ marginBottom: '0.75rem' }}>
        <div className="ins-figure">
          <span className="ins-figure-label">Calls handled</span>
          <strong className="ins-figure-value">{answeredCalls}</strong>
          <span className="ins-sub">{totalCalls} total calls ({totalMinutes} conversation mins)</span>
        </div>
        <div className="ins-figure">
          <span className="ins-figure-label">Leads created</span>
          <strong className="ins-figure-value" style={{ color: '#166534' }}>{leadsCreated}</strong>
          <span className="ins-sub">inbound inquiries saved</span>
        </div>
        <div className="ins-figure">
          <span className="ins-figure-label">Est. value secured</span>
          <strong className="ins-figure-value" style={{ color: '#166534' }}>
            {formatMoney(estimatedRevenue)}
          </strong>
          <span className="ins-sub">
            {voice.conversionRate !== undefined && voice.conversionRate < 1
              ? `at ${Math.round(voice.conversionRate * 100)}% lead conversion`
              : 'from phone leads'}
          </span>
        </div>
      </div>

      {missedCalls > 0 ? (
        <p className="ins-sub" style={{ color: '#b45309' }}>
          {missedCalls} call{missedCalls === 1 ? '' : 's'} were missed or sent to voicemail.
        </p>
      ) : (
        <p className="ins-sub">
          AI assistant answered 100% of incoming inquiries when the phone rang.
        </p>
      )}

      <div className="ins-card-foot" style={{ marginTop: '0.75rem' }}>
        <span>Tracked through your AI receptionist phone number.</span>
        <Link className="ins-inline-link" href={`${basePath}/voice-calls`}>Call history →</Link>
      </div>
    </section>
  );
}
