export type MexicoCodeFamily = {
  name: string;
  edition: string;
  model: string;
  effectiveYear?: number;
};

export type MexicoStateProfile = {
  stateCode: string;
  stateName: string;
  country: 'MX';
  licensingBoard: string;
  licensingUrl: string;
  codes: {
    building: MexicoCodeFamily;
    electrical: MexicoCodeFamily;
    mechanical: MexicoCodeFamily;
    plumbing: MexicoCodeFamily;
  };
  climateZone: string;
  specialRules: string[];
  basePermitFee: number;
  estAverageFee: number;
};

/**
 * Authoritative Mexican National Standards (NOMs) & State/Municipal Code Adoptions Registry.
 * Grounded in Secretaría de Energía (SENER / NOM-001-SEDE), Secretaría de Economía (SE / NMX),
 * CONAGUA, CONUEE (NOM-020-ENER), and Municipal Development Authorities (Desarrollo Urbano y Obras Públicas).
 */
export const MEXICO_CODE_REGISTRY: Record<string, MexicoStateProfile> = {
  CDMX: {
    stateCode: 'CDMX',
    stateName: 'Ciudad de México',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano y Vivienda (SEDUVI) / Colegio de Ingenieros Civiles (DRO)',
    licensingUrl: 'https://www.seduvi.cdmx.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Distrito Federal y Normas Técnicas Complementarias (NTC 2023)', edition: '2023', model: 'RCDF' },
      electrical: { name: 'NOM-001-SEDE-2012 / 2018 (Instalaciones Eléctricas - Utilización)', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Eficiencia Energética en Edificaciones / Aislamiento Térmico)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Normas Técnicas Complementarias de Instalaciones Hidráulicas y Sanitarias / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada / Alta Sismicidad (Zona Lacustre III)',
    specialRules: [
      'director_responsable_de_obra_dro_mandate',
      'ntc_diseno_sismico_estricto',
      'licencia_de_construccion_o_aviso_de_obra',
      'impermeabilizacion_elastomerica_o_prefabricada',
    ],
    basePermitFee: 1600,
    estAverageFee: 2800,
  },
  NL: {
    stateCode: 'NL',
    stateName: 'Nuevo León',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano y Obras Públicas de Monterrey / San Pedro Garza García',
    licensingUrl: 'https://www.monterrey.gob.mx/sedue',
    codes: {
      building: { name: 'Ley de Asentamientos Humanos y Reglamento de Zonificación y Construcción de Nuevo León', edition: '2022', model: 'LAHN' },
      electrical: { name: 'NOM-001-SEDE-2012 (Instalaciones Eléctricas / CFE División Golfo Norte)', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 / NOM-008-SEDG (Instalaciones de Aprovechamiento de Gas)', edition: '2020', model: 'NOM-ENER' },
      plumbing: { name: 'Servicios de Agua y Drenaje de Monterrey (SADM) / NOM-001-CONAGUA', edition: '2021', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Semiárida Extrema (Calor Extremo y Viento)',
    specialRules: [
      'aislamiento_termico_para_techos_nom_018_ener',
      'licencia_de_construccion_municipal',
      'corresponsable_en_seguridad_estructural',
    ],
    basePermitFee: 1800,
    estAverageFee: 3100,
  },
  JAL: {
    stateCode: 'JAL',
    stateName: 'Jalisco',
    country: 'MX',
    licensingBoard: 'Dirección de Obras Públicas de Guadalajara / Zapopan / Colegio de Arquitectos de Jalisco',
    licensingUrl: 'https://guadalajara.gob.mx/tramites/obras-publicas',
    codes: {
      building: { name: 'Código Urbano para el Estado de Jalisco y Reglamento de Edificación Municipal', edition: '2022', model: 'CUJ' },
      electrical: { name: 'NOM-001-SEDE-2012 (Instalaciones Eléctricas / CFE División Jalisco)', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 / NOM-004-SEDG', edition: '2020', model: 'NOM-ENER' },
      plumbing: { name: 'SIAPA (Sistema Intermunicipal de Agua Potable y Alcantarillado) / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada Subhúmeda / Zona Sísmica Media',
    specialRules: [
      'licencia_municipal_de_edificacion',
      'dictamen_de_perito_dro_registrado',
      'impermeabilizacion_acrilica_y_termica',
    ],
    basePermitFee: 1500,
    estAverageFee: 2600,
  },
  MEX: {
    stateCode: 'MEX',
    stateName: 'Estado de México',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano e Infraestructura del Estado de México / Municipios',
    licensingUrl: 'https://sedui.edomex.gob.mx',
    codes: {
      building: { name: 'Libro Quinto del Código Administrativo del Estado de México (Desarrollo Urbano y Vivienda)', edition: '2023', model: 'CAEM' },
      electrical: { name: 'NOM-001-SEDE-2012 (Instalaciones Eléctricas)', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Envolvente Térmica)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Comisión del Agua del Estado de México (CAEM) / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada y Fría de Montaña',
    specialRules: ['perito_responsable_de_obra', 'licencia_de_obra_menor_o_mayor'],
    basePermitFee: 1400,
    estAverageFee: 2400,
  },
  BCN: {
    stateCode: 'BCN',
    stateName: 'Baja California',
    country: 'MX',
    licensingBoard: 'Dirección de Administración Urbana de Tijuana / Mexicali / Colegio de Ingenieros Civiles',
    licensingUrl: 'https://tijuana.gob.mx/dependencias/dau',
    codes: {
      building: { name: 'Reglamento de Edificaciones para el Municipio de Tijuana / Mexicali', edition: '2022', model: 'REBC' },
      electrical: { name: 'NOM-001-SEDE-2012 / CFE División Baja California', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Aislamiento Extremo en Clima Desértico)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CESPT (Comisión Estatal de Servicios Públicos de Tijuana) / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Sísmica Extrema (Falla de San Andrés) / Calor Desértico',
    specialRules: ['alta_resistencia_sismica', 'aislamiento_termico_obligatorio_r19', 'perito_dro_municipal'],
    basePermitFee: 1700,
    estAverageFee: 2900,
  },
  BCS: {
    stateCode: 'BCS',
    stateName: 'Baja California Sur',
    country: 'MX',
    licensingBoard: 'Dirección General de Desarrollo Urbano y Ecología de Los Cabos / La Paz',
    licensingUrl: 'https://loscabos.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Los Cabos / La Paz', edition: '2022', model: 'RCBCS' },
      electrical: { name: 'NOM-001-SEDE-2012 (Instalaciones Eléctricas)', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'OOMSAPAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Costera de Alto Impacto de Huracanes',
    specialRules: ['resistencia_vientos_huracanados_categoria_5', 'anclaje_estructural_costero'],
    basePermitFee: 1750,
    estAverageFee: 3000,
  },
  ROO: {
    stateCode: 'ROO',
    stateName: 'Quintana Roo',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano de Benito Juárez (Cancún) / Solidaridad (Playa del Carmen)',
    licensingUrl: 'https://cancun.gob.mx/tramites-desarrollo-urbano',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Benito Juárez (Cancún / Riviera Maya)', edition: '2022', model: 'RCROO' },
      electrical: { name: 'NOM-001-SEDE-2012 / CFE División Peninsular', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Clima Tropical Húmedo)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Aguakan / CAPA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Caribeña de Máximo Riesgo de Huracanes y Lluvia Torrencial',
    specialRules: [
      'diseno_antihuracan_vientos_250kmh',
      'sistema_de_impermeabilizacion_prefabricada_termofusionada',
      'director_responsable_de_obra_dro_cancun',
    ],
    basePermitFee: 1850,
    estAverageFee: 3200,
  },
  YUC: {
    stateCode: 'YUC',
    stateName: 'Yucatán',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano del Ayuntamiento de Mérida',
    licensingUrl: 'https://merida.gob.mx/desarrollourbano',
    codes: {
      building: { name: 'Reglamento de Construcciones del Municipio de Mérida', edition: '2022', model: 'RCYUC' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'JAPAY / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Cálida Subhúmeda / Huracanes',
    specialRules: ['vientos_huracanados_peninsular', 'impermeabilizacion_resistente_humedad_salina'],
    basePermitFee: 1450,
    estAverageFee: 2500,
  },
  GTO: {
    stateCode: 'GTO',
    stateName: 'Guanajuato',
    country: 'MX',
    licensingBoard: 'Dirección General de Desarrollo Urbano de León / Irapuato',
    licensingUrl: 'https://leon.gob.mx',
    codes: {
      building: { name: 'Código Territorial para el Estado y los Municipios de Guanajuato', edition: '2022', model: 'CTGTO' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SAPAL / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada / Bajío',
    specialRules: ['licencia_de_construccion_municipal', 'perito_especializado_dro'],
    basePermitFee: 1350,
    estAverageFee: 2300,
  },
  PUE: {
    stateCode: 'PUE',
    stateName: 'Puebla',
    country: 'MX',
    licensingBoard: 'Secretaría de Gestión y Desarrollo Urbano del Municipio de Puebla',
    licensingUrl: 'https://pueblacapital.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Municipio de Puebla', edition: '2022', model: 'RCPUE' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Agua de Puebla para Todos / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada de Altiplano / Sismicidad Moderada',
    specialRules: ['perito_dro_puebla', 'conservacion_centro_historico_inah'],
    basePermitFee: 1400,
    estAverageFee: 2400,
  },
  QRO: {
    stateCode: 'QRO',
    stateName: 'Querétaro',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Sostenible del Municipio de Querétaro',
    licensingUrl: 'https://municipiodequeretaro.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Querétaro', edition: '2022', model: 'RCQRO' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Comisión Estatal de Aguas (CEA) / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Semiárida Templada',
    specialRules: ['licencia_de_construccion_municipal', 'perito_dro_queretaro'],
    basePermitFee: 1500,
    estAverageFee: 2600,
  },
  VER: {
    stateCode: 'VER',
    stateName: 'Veracruz',
    country: 'MX',
    licensingBoard: 'Dirección de Obras Públicas y Desarrollo Urbano de Veracruz / Boca del Río / Xalapa',
    licensingUrl: 'https://veracruzmunicipio.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Estado de Veracruz de Ignacio de la Llave', edition: '2022', model: 'RCVER' },
      electrical: { name: 'NOM-001-SEDE-2012 / CFE División Oriente', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Grupo MAS / CMAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Tropical Húmeda / Vientos del Norte y Huracanes',
    specialRules: ['resistencia_vientos_del_norte_y_humedad_costera', 'impermeabilizacion_continua'],
    basePermitFee: 1400,
    estAverageFee: 2400,
  },
  SON: {
    stateCode: 'SON',
    stateName: 'Sonora',
    country: 'MX',
    licensingBoard: 'Dirección General de Desarrollo Urbano de Hermosillo / Cajeme',
    licensingUrl: 'https://hermosillo.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Hermosillo', edition: '2022', model: 'RCSON' },
      electrical: { name: 'NOM-001-SEDE-2012 / CFE División Noroeste', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Aislamiento Máximo por Calor Extremo)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Agua de Hermosillo / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Desértica Extrema (Temperaturas > 45°C)',
    specialRules: ['aislamiento_termico_obligatorio_nom_018', 'aire_acondicionado_alta_eficiencia'],
    basePermitFee: 1450,
    estAverageFee: 2500,
  },
  CHH: {
    stateCode: 'CHH',
    stateName: 'Chihuahua',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano y Ecología de Chihuahua / Ciudad Juárez',
    licensingUrl: 'https://municipiochihuahua.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones y Normas Técnicas para el Municipio de Chihuahua', edition: '2022', model: 'RCCHH' },
      electrical: { name: 'NOM-001-SEDE-2012 / CFE División Norte', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011 (Clima Extremo Calor/Heladas)', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'JMAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Árida Continental (Heladas Invernales y Calor Extremo)',
    specialRules: ['resistencia_heladas_congelacion_tuberias', 'aislamiento_termico_integral'],
    basePermitFee: 1400,
    estAverageFee: 2450,
  },
  TAM: {
    stateCode: 'TAM',
    stateName: 'Tamaulipas',
    country: 'MX',
    licensingBoard: 'Dirección de Obras Públicas y Desarrollo Urbano de Reynosa / Tampico / Matamoros',
    licensingUrl: 'https://reynosa.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Estado de Tamaulipas', edition: '2022', model: 'RCTAM' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'COMAPA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Costera / Cálida Semiárida',
    specialRules: ['vientos_costeros_huracanados', 'impermeabilizacion_resistente'],
    basePermitFee: 1350,
    estAverageFee: 2350,
  },
  COA: {
    stateCode: 'COA',
    stateName: 'Coahuila',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano de Saltillo / Torreón',
    licensingUrl: 'https://saltillo.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Saltillo / Torreón', edition: '2022', model: 'RCCOA' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Aguas de Saltillo / SIMAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Árida / Templada de Sierra',
    specialRules: ['aislamiento_termico_clima_extremo', 'perito_dro_coahuila'],
    basePermitFee: 1350,
    estAverageFee: 2300,
  },
  SIN: {
    stateCode: 'SIN',
    stateName: 'Sinaloa',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano y Ecología de Culiacán / Mazatlán',
    licensingUrl: 'https://culiacan.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Culiacán / Mazatlán', edition: '2022', model: 'RCSIN' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'JAPAC / JUMAPAM / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Costera Tropical / Humedad Extrema',
    specialRules: ['vientos_huracanados_pacifico', 'impermeabilizacion_humedad_costera'],
    basePermitFee: 1400,
    estAverageFee: 2400,
  },
  SLP: {
    stateCode: 'SLP',
    stateName: 'San Luis Potosí',
    country: 'MX',
    licensingBoard: 'Dirección de Administración y Desarrollo Urbano de San Luis Potosí',
    licensingUrl: 'https://sanluis.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Municipio de San Luis Potosí', edition: '2022', model: 'RCSLP' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'INTERAPAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada Semiárida / Huasteca Tropical',
    specialRules: ['licencia_municipal_de_construccion', 'perito_dro_slp'],
    basePermitFee: 1300,
    estAverageFee: 2250,
  },
  AGU: {
    stateCode: 'AGU',
    stateName: 'Aguascalientes',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano del Municipio de Aguascalientes (SEDUM)',
    licensingUrl: 'https://ags.gob.mx',
    codes: {
      building: { name: 'Código Urbano para el Estado de Aguascalientes', edition: '2022', model: 'CUAGU' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CCAPAMA / MIAA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada Semiárida',
    specialRules: ['perito_responsable_de_obra_sedum', 'licencia_de_construccion'],
    basePermitFee: 1300,
    estAverageFee: 2200,
  },
  MOR: {
    stateCode: 'MOR',
    stateName: 'Morelos',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano y Obras Públicas de Cuernavaca',
    licensingUrl: 'https://cuernavaca.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción del Municipio de Cuernavaca', edition: '2022', model: 'RCMOR' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SAPAC / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Cálida Templada / Sísmica',
    specialRules: ['perito_dro_morelos', 'diseno_sismico_regional'],
    basePermitFee: 1350,
    estAverageFee: 2300,
  },
  HID: {
    stateCode: 'HID',
    stateName: 'Hidalgo',
    country: 'MX',
    licensingBoard: 'Secretaría de Obras Públicas y Desarrollo Urbano de Pachuca',
    licensingUrl: 'https://pachuca.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Pachuca de Soto', edition: '2022', model: 'RCHID' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CAASIM / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada de Altiplano y Viento',
    specialRules: ['licencia_municipal_pachuca', 'perito_dro_hidalgo'],
    basePermitFee: 1250,
    estAverageFee: 2150,
  },
  MIC: {
    stateCode: 'MIC',
    stateName: 'Michoacán',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano y Movilidad de Morelia',
    licensingUrl: 'https://morelia.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones y Servicios Urbanos para el Municipio de Morelia', edition: '2022', model: 'RCMIC' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'OOAPAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada y Costa Sísmica',
    specialRules: ['diseno_sismico_costa_michocan', 'perito_dro_morelia'],
    basePermitFee: 1300,
    estAverageFee: 2250,
  },
  CHP: {
    stateCode: 'CHP',
    stateName: 'Chiapas',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano de Tuxtla Gutiérrez / Tapachula',
    licensingUrl: 'https://tuxtla.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Tuxtla Gutiérrez', edition: '2022', model: 'RCCHP' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SMAPA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Tropical / Máxima Sismicidad de Subducción',
    specialRules: ['diseno_sismico_zona_d_alta', 'perito_dro_chiapas'],
    basePermitFee: 1250,
    estAverageFee: 2150,
  },
  OAX: {
    stateCode: 'OAX',
    stateName: 'Oaxaca',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano del Municipio de Oaxaca de Juárez',
    licensingUrl: 'https://municipiodeoaxaca.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción y Seguridad Estructural de Oaxaca', edition: '2022', model: 'RCOAX' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SOAPA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona de Muy Alta Sismicidad / Costa y Valles',
    specialRules: ['alta_sismicidad_refuerzo_estructural', 'centro_historico_patrimonio_inah'],
    basePermitFee: 1300,
    estAverageFee: 2200,
  },
  GRO: {
    stateCode: 'GRO',
    stateName: 'Guerrero',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano y Obras Públicas de Acapulco / Chilpancingo',
    licensingUrl: 'https://acapulco.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Municipio de Acapulco de Juárez', edition: '2022', model: 'RCGRO' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CAPAMA / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona de Huracanes Severos y Máxima Sismicidad (Brecha de Guerrero)',
    specialRules: ['resistencia_huracanes_categoria_5_otis', 'resistencia_sismica_maxima', 'perito_dro_acapulco'],
    basePermitFee: 1550,
    estAverageFee: 2700,
  },
  TAB: {
    stateCode: 'TAB',
    stateName: 'Tabasco',
    country: 'MX',
    licensingBoard: 'Dirección de Obras, Ordenamiento Territorial y Servicios Municipales de Villahermosa',
    licensingUrl: 'https://villahermosa.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Municipio de Centro (Villahermosa)', edition: '2022', model: 'RCTAB' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Tropical Húmeda / Inundaciones y Lluvias Intensas',
    specialRules: ['impermeabilizacion_continua_lluvias_intensas', 'proteccion_humedad_nivel_freatico'],
    basePermitFee: 1300,
    estAverageFee: 2250,
  },
  ZAC: {
    stateCode: 'ZAC',
    stateName: 'Zacatecas',
    country: 'MX',
    licensingBoard: 'Secretaría de Desarrollo Urbano y Medio Ambiente de Zacatecas / Guadalupe',
    licensingUrl: 'https://capitaldezacatecas.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Zacatecas', edition: '2022', model: 'RCZAC' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'JIAPAZ / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada Fría de Altiplano',
    specialRules: ['centro_historico_patrimonio_inah', 'perito_dro_zacatecas'],
    basePermitFee: 1250,
    estAverageFee: 2150,
  },
  DUR: {
    stateCode: 'DUR',
    stateName: 'Durango',
    country: 'MX',
    licensingBoard: 'Dirección Municipal de Desarrollo Urbano de Durango',
    licensingUrl: 'https://municipiodurango.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones para el Municipio de Durango', edition: '2022', model: 'RCDUR' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'Aguas del Municipio de Durango (AMD) / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada Semiárida y Sierra Fría',
    specialRules: ['licencia_de_construccion_durango', 'perito_dro_durango'],
    basePermitFee: 1250,
    estAverageFee: 2150,
  },
  NAY: {
    stateCode: 'NAY',
    stateName: 'Nayarit',
    country: 'MX',
    licensingBoard: 'Dirección General de Desarrollo Urbano y Ecología de Tepic / Bahía de Banderas',
    licensingUrl: 'https://tepic.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Tepic / Bahía de Banderas', edition: '2022', model: 'RCNAY' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SIAPA Tepic / OROMAPAS / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Costera Tropical y Sísmica',
    specialRules: ['vientos_costeros_pacifico', 'anclaje_estructural_costero'],
    basePermitFee: 1350,
    estAverageFee: 2350,
  },
  COL: {
    stateCode: 'COL',
    stateName: 'Colima',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano de Colima / Manzanillo',
    licensingUrl: 'https://colima.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Municipio de Colima / Manzanillo', edition: '2022', model: 'RCCOL' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CIAPACOV / INPLAN / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona de Muy Alta Sismicidad y Huracanes Costeros',
    specialRules: ['maxima_resistencia_sismica_subduccion', 'resistencia_huracanes_manzanillo'],
    basePermitFee: 1350,
    estAverageFee: 2350,
  },
  TLA: {
    stateCode: 'TLA',
    stateName: 'Tlaxcala',
    country: 'MX',
    licensingBoard: 'Dirección de Obras Públicas y Desarrollo Urbano de Tlaxcala',
    licensingUrl: 'https://tlaxcalacapital.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcción para el Estado de Tlaxcala', edition: '2022', model: 'RCTLA' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'CAPAM / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Templada de Altiplano',
    specialRules: ['licencia_municipal_tlaxcala', 'perito_dro_tlaxcala'],
    basePermitFee: 1200,
    estAverageFee: 2100,
  },
  CAM: {
    stateCode: 'CAM',
    stateName: 'Campeche',
    country: 'MX',
    licensingBoard: 'Dirección de Desarrollo Urbano del Municipio de Campeche / Carmen',
    licensingUrl: 'https://municipiodecampeche.gob.mx',
    codes: {
      building: { name: 'Reglamento de Construcciones del Municipio de Campeche', edition: '2022', model: 'RCCAM' },
      electrical: { name: 'NOM-001-SEDE-2012', edition: '2018', model: 'NOM-SEDE' },
      mechanical: { name: 'NOM-020-ENER-2011', edition: '2011', model: 'NOM-ENER' },
      plumbing: { name: 'SMAPAC / NOM-001-CONAGUA', edition: '2020', model: 'NOM-CONAGUA' },
    },
    climateZone: 'Zona Tropical Cálida Húmeda / Costa del Golfo',
    specialRules: ['proteccion_contra_inundacion_y_salinidad', 'impermeabilizacion_clima_tropical'],
    basePermitFee: 1300,
    estAverageFee: 2250,
  },
};

const MEXICO_STATES_TO_CODE: Record<string, string> = {
  'ciudad de mexico': 'CDMX',
  'ciudad de méxico': 'CDMX',
  cdmx: 'CDMX',
  df: 'CDMX',
  'distrito federal': 'CDMX',
  'nuevo leon': 'NL',
  'nuevo león': 'NL',
  jalisco: 'JAL',
  'estado de mexico': 'MEX',
  'estado de méxico': 'MEX',
  edomex: 'MEX',
  'baja california': 'BCN',
  'baja california norte': 'BCN',
  'baja california sur': 'BCS',
  'quintana roo': 'ROO',
  yucatan: 'YUC',
  yucatán: 'YUC',
  guanajuato: 'GTO',
  puebla: 'PUE',
  queretaro: 'QRO',
  querétaro: 'QRO',
  veracruz: 'VER',
  sonora: 'SON',
  chihuahua: 'CHH',
  tamaulipas: 'TAM',
  coahuila: 'COA',
  sinaloa: 'SIN',
  'san luis potosi': 'SLP',
  'san luis potosí': 'SLP',
  aguascalientes: 'AGU',
  morelos: 'MOR',
  hidalgo: 'HID',
  michoacan: 'MIC',
  michoacán: 'MIC',
  chiapas: 'CHP',
  oaxaca: 'OAX',
  guerrero: 'GRO',
  tabasco: 'TAB',
  zacatecas: 'ZAC',
  durango: 'DUR',
  nayarit: 'NAY',
  colima: 'COL',
  tlaxcala: 'TLA',
  campeche: 'CAM',
};

/**
 * Normalizes any string representation of a Mexican state to its official code.
 */
export function normalizeMexicoStateCode(input?: string | null): string | null {
  if (!input) return null;
  const trimmed = input.trim();
  const upper = trimmed.toUpperCase();
  if (MEXICO_CODE_REGISTRY[upper]) return upper;

  const lower = trimmed.toLowerCase();
  if (MEXICO_STATES_TO_CODE[lower]) return MEXICO_STATES_TO_CODE[lower];

  return null;
}
