export type StateCodeFamily = {
  name: string;
  edition: string;
  model: string;
  effectiveYear?: number;
};

export type StateCodeProfile = {
  stateCode: string;
  stateName: string;
  fips: string;
  licensingBoard: string;
  licensingUrl: string;
  codes: {
    building: StateCodeFamily;
    electrical: StateCodeFamily;
    mechanical: StateCodeFamily;
    plumbing: StateCodeFamily;
  };
  climateZone: string;
  iceBarrierRequired: boolean;
  specialRules: string[];
  basePermitFee: number;
  estAverageFee: number;
};

/**
 * Authoritative 50-State + DC Building Code Adoptions Registry.
 * Grounded in ICC (International Code Council), NFPA (NEC), IAPMO (UPC/UMC),
 * and state building commission administrative adoptions.
 */
export const STATE_CODE_REGISTRY: Record<string, StateCodeProfile> = {
  AL: {
    stateCode: 'AL',
    stateName: 'Alabama',
    fips: '01',
    licensingBoard: 'Alabama Home Builders Licensure Board / Licensing Board for General Contractors',
    licensingUrl: 'https://hblb.alabama.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 2-3 (Warm-Humid)',
    iceBarrierRequired: false,
    specialRules: ['coastal_windborne_debris_zone'],
    basePermitFee: 65,
    estAverageFee: 105,
  },
  AK: {
    stateCode: 'AK',
    stateName: 'Alaska',
    fips: '02',
    licensingBoard: 'Alaska Division of Corporations, Business and Professional Licensing',
    licensingUrl: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/ConstructionContractors.aspx',
    codes: {
      building: { name: '2018 International Residential Code (IRC) with Alaska Amendments', edition: '2018', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2018 International Mechanical Code (IMC)', edition: '2018', model: 'IMC' },
      plumbing: { name: '2018 Uniform Plumbing Code (UPC)', edition: '2018', model: 'UPC' },
    },
    climateZone: 'Zone 7-8 (Subarctic / Arctic)',
    iceBarrierRequired: true,
    specialRules: ['heavy_snow_load', 'permafrost_foundation', 'enhanced_ice_barrier_depth'],
    basePermitFee: 95,
    estAverageFee: 165,
  },
  AZ: {
    stateCode: 'AZ',
    stateName: 'Arizona',
    fips: '04',
    licensingBoard: 'Arizona Registrar of Contractors (ROC)',
    licensingUrl: 'https://roc.az.gov',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 2B (Hot-Dry)',
    iceBarrierRequired: false,
    specialRules: ['extreme_heat_roof_ventilation', 'solar_readiness'],
    basePermitFee: 80,
    estAverageFee: 135,
  },
  AR: {
    stateCode: 'AR',
    stateName: 'Arkansas',
    fips: '05',
    licensingBoard: 'Arkansas Contractors Licensing Board',
    licensingUrl: 'https://aclb.arkansas.gov',
    codes: {
      building: { name: '2021 Arkansas Fire Prevention Code (IRC based)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 Arkansas Mechanical Code', edition: '2021', model: 'IMC' },
      plumbing: { name: '2018 Arkansas Plumbing Code', edition: '2018', model: 'IPC' },
    },
    climateZone: 'Zone 3A (Warm-Humid)',
    iceBarrierRequired: false,
    specialRules: ['high_wind_fastening'],
    basePermitFee: 60,
    estAverageFee: 95,
  },
  CA: {
    stateCode: 'CA',
    stateName: 'California',
    fips: '06',
    licensingBoard: 'California Contractors State License Board (CSLB)',
    licensingUrl: 'https://www.cslb.ca.gov',
    codes: {
      building: { name: 'California Residential Code (CRC / Title 24 Part 2.5)', edition: '2022/2025', model: 'CRC' },
      electrical: { name: 'California Electrical Code (CEC / Title 24 Part 3)', edition: '2022', model: 'CEC' },
      mechanical: { name: 'California Mechanical Code (CMC / Title 24 Part 4)', edition: '2022', model: 'CMC' },
      plumbing: { name: 'California Plumbing Code (CPC / Title 24 Part 5)', edition: '2022', model: 'CPC' },
    },
    climateZone: 'Zone 3-4 (Marine / Mediterranean / Semi-Arid)',
    iceBarrierRequired: false,
    specialRules: [
      'wildland_urban_interface_fire_chapter_7a',
      'title_24_energy_cool_roof',
      'solar_photovoltaic_mandate',
      'calgreen_tier_1',
    ],
    basePermitFee: 120,
    estAverageFee: 210,
  },
  CO: {
    stateCode: 'CO',
    stateName: 'Colorado',
    fips: '08',
    licensingBoard: 'Colorado Department of Regulatory Agencies (DORA)',
    licensingUrl: 'https://dora.colorado.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC) (Local Adoptions)', edition: '2021', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC / Colorado State Board of Electricity)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC / Colorado State Plumbing Board)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5-6 (Cold / Semi-Arid)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory', 'class_4_impact_resistance_hail', 'high_altitude_snow_load'],
    basePermitFee: 85,
    estAverageFee: 145,
  },
  CT: {
    stateCode: 'CT',
    stateName: 'Connecticut',
    fips: '09',
    licensingBoard: 'Connecticut Department of Consumer Protection (DCP)',
    licensingUrl: 'https://portal.ct.gov/dcp',
    codes: {
      building: { name: '2022 Connecticut State Building Code (2021 IRC)', edition: '2022', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory_24_inch', 'home_improvement_contractor_registration'],
    basePermitFee: 75,
    estAverageFee: 130,
  },
  DE: {
    stateCode: 'DE',
    stateName: 'Delaware',
    fips: '10',
    licensingBoard: 'Delaware Division of Professional Regulation',
    licensingUrl: 'https://dpr.delaware.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['coastal_wind_exposure'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  FL: {
    stateCode: 'FL',
    stateName: 'Florida',
    fips: '12',
    licensingBoard: 'Florida Department of Business and Professional Regulation (DBPR / CILB)',
    licensingUrl: 'https://www.myfloridalicense.com/DBPR',
    codes: {
      building: { name: 'Florida Building Code (FBC 8th Edition - Residential)', edition: '2023', model: 'FBC' },
      electrical: { name: '2020/2023 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: 'Florida Building Code - Mechanical', edition: '2023', model: 'FBC-M' },
      plumbing: { name: 'Florida Building Code - Plumbing', edition: '2023', model: 'FBC-P' },
    },
    climateZone: 'Zone 1-2 (Very Hot / Humid / Tropical)',
    iceBarrierRequired: false,
    specialRules: [
      'fbc_hvhz_high_velocity_hurricane_zone',
      'sealed_roof_deck_mandate',
      'miami_dade_noa_product_approval',
      'secondary_water_barrier_self_adhering',
    ],
    basePermitFee: 110,
    estAverageFee: 195,
  },
  GA: {
    stateCode: 'GA',
    stateName: 'Georgia',
    fips: '13',
    licensingBoard: 'Georgia State Licensing Board for Residential and General Contractors',
    licensingUrl: 'https://sos.ga.gov',
    codes: {
      building: { name: 'Georgia State Minimum Standard One and Two Family Dwelling Code (2018/2024 IRC)', edition: '2018/2024', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2018 International Mechanical Code (IMC)', edition: '2018', model: 'IMC' },
      plumbing: { name: '2018 International Plumbing Code (IPC)', edition: '2018', model: 'IPC' },
    },
    climateZone: 'Zone 3A (Warm-Humid)',
    iceBarrierRequired: false,
    specialRules: ['coastal_hurricane_wind_provisions'],
    basePermitFee: 70,
    estAverageFee: 120,
  },
  HI: {
    stateCode: 'HI',
    stateName: 'Hawaii',
    fips: '15',
    licensingBoard: 'Hawaii Professional and Vocational Licensing Division (DCCA / Contractors License Board)',
    licensingUrl: 'https://cca.hawaii.gov/pvl/boards/contractor',
    codes: {
      building: { name: '2018 Hawaii State Building Code (2018 IRC)', edition: '2018', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2018 Uniform Mechanical Code (UMC)', edition: '2018', model: 'UMC' },
      plumbing: { name: '2018 Uniform Plumbing Code (UPC)', edition: '2018', model: 'UPC' },
    },
    climateZone: 'Zone 1 (Tropical Marine)',
    iceBarrierRequired: false,
    specialRules: ['high_wind_hurricane_straps', 'termite_resistant_treated_lumber', 'salt_spray_corrosion_fasteners'],
    basePermitFee: 130,
    estAverageFee: 225,
  },
  ID: {
    stateCode: 'ID',
    stateName: 'Idaho',
    fips: '16',
    licensingBoard: 'Idaho Division of Occupational and Professional Licenses (DOPL)',
    licensingUrl: 'https://dopl.idaho.gov',
    codes: {
      building: { name: '2018 Idaho Residential Code (IRC)', edition: '2018', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2018 International Mechanical Code (IMC)', edition: '2018', model: 'IMC' },
      plumbing: { name: '2017 Idaho State Plumbing Code (UPC)', edition: '2017', model: 'UPC' },
    },
    climateZone: 'Zone 5-6 (Cold / Semi-Arid)',
    iceBarrierRequired: true,
    specialRules: ['snow_load_provisions', 'ice_barrier_mandatory'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  IL: {
    stateCode: 'IL',
    stateName: 'Illinois',
    fips: '17',
    licensingBoard: 'Illinois Department of Financial and Professional Regulation (IDFPR) / Local Municipalities',
    licensingUrl: 'https://idfpr.illinois.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC) (Local Municipal Adoptions / Chicago Building Code)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC / Chicago Electrical Code)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: 'Illinois Plumbing Code (77 Ill. Adm. Code 890)', edition: '2020', model: 'ILPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['illinois_plumbing_license_mandate', 'ice_barrier_mandatory', 'chicago_conduit_mandate'],
    basePermitFee: 85,
    estAverageFee: 155,
  },
  IN: {
    stateCode: 'IN',
    stateName: 'Indiana',
    fips: '18',
    licensingBoard: 'Indiana Professional Licensing Agency (IPLA) / Fire Prevention and Building Safety Commission',
    licensingUrl: 'https://www.in.gov/pla',
    codes: {
      building: { name: '2020 Indiana Residential Code (2018 IRC with IN Amendments)', edition: '2020', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2020 Indiana Mechanical Code (2018 IMC)', edition: '2020', model: 'IMC' },
      plumbing: { name: '2012 Indiana Plumbing Code (IPC)', edition: '2012', model: 'IPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  IA: {
    stateCode: 'IA',
    stateName: 'Iowa',
    fips: '19',
    licensingBoard: 'Iowa Division of Labor / Plumbing and Mechanical Systems Board',
    licensingUrl: 'https://www.iowadivisionoflabor.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 5-6 (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory'],
    basePermitFee: 65,
    estAverageFee: 110,
  },
  KS: {
    stateCode: 'KS',
    stateName: 'Kansas',
    fips: '20',
    licensingBoard: 'Kansas Local Municipalities / Kansas Roofing Registration',
    licensingUrl: 'https://ag.ks.gov/business/roofing-contractor-registration',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['kansas_attorney_general_roofing_registration', 'high_wind_tornado_fastening'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  KY: {
    stateCode: 'KY',
    stateName: 'Kentucky',
    fips: '21',
    licensingBoard: 'Kentucky Department of Housing, Buildings and Construction (DHBC)',
    licensingUrl: 'https://dhbc.ky.gov',
    codes: {
      building: { name: '2018 Kentucky Residential Code (IRC)', edition: '2018', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2018 Kentucky Mechanical Code', edition: '2018', model: 'IMC' },
      plumbing: { name: '2018 Kentucky State Plumbing Code', edition: '2018', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['state_plumbing_license_mandate', 'ice_barrier_mandatory'],
    basePermitFee: 65,
    estAverageFee: 110,
  },
  LA: {
    stateCode: 'LA',
    stateName: 'Louisiana',
    fips: '22',
    licensingBoard: 'Louisiana State Licensing Board for Contractors (LSLBC)',
    licensingUrl: 'https://lslbc.louisiana.gov',
    codes: {
      building: { name: '2021 Louisiana State Uniform Construction Code (2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 2A (Hot-Humid)',
    iceBarrierRequired: false,
    specialRules: ['coastal_hurricane_wind_mitigation', 'sealed_roof_deck_incentive'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  ME: {
    stateCode: 'ME',
    stateName: 'Maine',
    fips: '23',
    licensingBoard: 'Maine Uniform Building and Energy Code Board (MUBEC)',
    licensingUrl: 'https://www.maine.gov/dacf/php/mubec',
    codes: {
      building: { name: '2021 Maine Uniform Building and Energy Code (2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 6A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory_extended', 'heavy_snow_load'],
    basePermitFee: 70,
    estAverageFee: 120,
  },
  MD: {
    stateCode: 'MD',
    stateName: 'Maryland',
    fips: '24',
    licensingBoard: 'Maryland Home Improvement Commission (MHIC / DLLR)',
    licensingUrl: 'https://www.dllr.state.md.us/license/mhic',
    codes: {
      building: { name: 'Maryland Building Performance Standards (2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['mhic_license_display_mandate', 'ice_barrier_mandatory'],
    basePermitFee: 80,
    estAverageFee: 135,
  },
  MA: {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    fips: '25',
    licensingBoard: 'Massachusetts Board of Building Regulations and Standards (BBRS / HIC & CSL)',
    licensingUrl: 'https://www.mass.gov/orgs/office-of-public-safety-and-inspections',
    codes: {
      building: { name: '780 CMR Massachusetts State Building Code (9th/10th Edition - 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '527 CMR 12.00 Massachusetts Electrical Code (2023 NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '248 CMR Uniform State Plumbing Code', edition: '2021', model: 'MAPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['construction_supervisor_license_csl', 'hic_registration', 'ice_barrier_mandatory_24_in'],
    basePermitFee: 90,
    estAverageFee: 160,
  },
  MI: {
    stateCode: 'MI',
    stateName: 'Michigan',
    fips: '26',
    licensingBoard: 'Michigan Department of Licensing and Regulatory Affairs (LARA / BCC)',
    licensingUrl: 'https://www.michigan.gov/lara/bureau-list/bcc',
    codes: {
      building: { name: '2015 Michigan Residential Code (MRC / 2015 IRC)', edition: '2015', model: 'MRC' },
      electrical: { name: '2023 Michigan Electrical Code (2023 NEC)', edition: '2023', model: 'MEC' },
      mechanical: { name: '2021 Michigan Mechanical Code (2021 IMC)', edition: '2021', model: 'MMC' },
      plumbing: { name: '2021 Michigan Plumbing Code (2021 IPC)', edition: '2021', model: 'MPC' },
    },
    climateZone: 'Zone 5A-6A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['pa_230_section_23a_statutory_notice', 'ice_barrier_24_inch_past_wall_line', 'two_roof_layers_max'],
    basePermitFee: 85,
    estAverageFee: 125,
  },
  MN: {
    stateCode: 'MN',
    stateName: 'Minnesota',
    fips: '27',
    licensingBoard: 'Minnesota Department of Labor and Industry (DLI)',
    licensingUrl: 'https://www.dli.mn.gov',
    codes: {
      building: { name: '2020 Minnesota Residential Code (2018 IRC)', edition: '2020', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2020 Minnesota Mechanical Code (IMC)', edition: '2020', model: 'IMC' },
      plumbing: { name: '2020 Minnesota Plumbing Code (UPC)', edition: '2020', model: 'UPC' },
    },
    climateZone: 'Zone 6-7 (Very Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory_extended', 'heavy_snow_load_drift_calculations', 'air_barrier_blower_door'],
    basePermitFee: 85,
    estAverageFee: 140,
  },
  MS: {
    stateCode: 'MS',
    stateName: 'Mississippi',
    fips: '28',
    licensingBoard: 'Mississippi State Board of Contractors (MSBOC)',
    licensingUrl: 'https://www.msboc.us',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 3A (Warm-Humid)',
    iceBarrierRequired: false,
    specialRules: ['coastal_high_wind_fastening'],
    basePermitFee: 60,
    estAverageFee: 100,
  },
  MO: {
    stateCode: 'MO',
    stateName: 'Missouri',
    fips: '29',
    licensingBoard: 'Missouri Local Municipalities / St. Louis & Kansas City Code Enforcement',
    licensingUrl: 'https://pr.mo.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC) (Local Adoptions)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC / UPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory_north_of_i44'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  MT: {
    stateCode: 'MT',
    stateName: 'Montana',
    fips: '30',
    licensingBoard: 'Montana Department of Labor and Industry (Business Standards Division)',
    licensingUrl: 'https://bsd.dli.mt.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 6 (Cold)',
    iceBarrierRequired: true,
    specialRules: ['heavy_snow_load', 'ice_barrier_mandatory'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  NE: {
    stateCode: 'NE',
    stateName: 'Nebraska',
    fips: '31',
    licensingBoard: 'Nebraska Department of Labor / State Electrical Division',
    licensingUrl: 'https://electrical.nebraska.gov',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory', 'hail_impact_resistant_shingle_incentive'],
    basePermitFee: 65,
    estAverageFee: 110,
  },
  NV: {
    stateCode: 'NV',
    stateName: 'Nevada',
    fips: '32',
    licensingBoard: 'Nevada State Contractors Board (NSCB)',
    licensingUrl: 'https://www.nscb.nv.gov',
    codes: {
      building: { name: '2018/2021 Northern/Southern Nevada Building Code Amendments (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 Uniform Mechanical Code (UMC)', edition: '2021', model: 'UMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 3B-5B (Dry / Desert to Alpine)',
    iceBarrierRequired: false,
    specialRules: ['extreme_heat_roof_ventilation', 'snow_provisions_in_washoe_carson'],
    basePermitFee: 85,
    estAverageFee: 145,
  },
  NH: {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    fips: '33',
    licensingBoard: 'New Hampshire State Building Code Review Board / Electricians & Plumbers Boards',
    licensingUrl: 'https://www.nh.gov/safety/boardsandcommissions/bcrb',
    codes: {
      building: { name: '2018/2021 New Hampshire State Building Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5-6 (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory', 'heavy_snow_loads'],
    basePermitFee: 70,
    estAverageFee: 120,
  },
  NJ: {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    fips: '34',
    licensingBoard: 'New Jersey Department of Community Affairs (DCA / Division of Codes and Standards)',
    licensingUrl: 'https://www.nj.gov/dca/divisions/codes',
    codes: {
      building: { name: 'New Jersey Uniform Construction Code (UCC / 2021 IRC NJ Edition)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 National Standard Plumbing Code (NSPC)', edition: '2021', model: 'NSPC' },
    },
    climateZone: 'Zone 4A-5A (Mixed-Humid / Cold)',
    iceBarrierRequired: true,
    specialRules: ['ucc_rehabilitation_subcode', 'home_improvement_contractor_registration_hic'],
    basePermitFee: 95,
    estAverageFee: 165,
  },
  NM: {
    stateCode: 'NM',
    stateName: 'New Mexico',
    fips: '35',
    licensingBoard: 'New Mexico Regulation and Licensing Department (Construction Industries Division / CID)',
    licensingUrl: 'https://www.rld.nm.gov/construction-industries-division',
    codes: {
      building: { name: '2021 New Mexico Residential Building Code (NMRBC / 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 New Mexico Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 New Mexico Mechanical Code (UMC)', edition: '2021', model: 'UMC' },
      plumbing: { name: '2021 New Mexico Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 3B-4B (Dry / High Elevation)',
    iceBarrierRequired: false,
    specialRules: ['high_altitude_ventilation', 'adobe_construction_standards'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  NY: {
    stateCode: 'NY',
    stateName: 'New York',
    fips: '36',
    licensingBoard: 'New York Department of State (Division of Building Standards and Codes) / NYC DOB',
    licensingUrl: 'https://dos.ny.gov/building-standards-and-codes',
    codes: {
      building: { name: '2020 Uniform Code of New York State (2018/2021 IRC / NYC Building Code)', edition: '2020/2024', model: 'IRC' },
      electrical: { name: '2017/2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2020 Mechanical Code of New York State (IMC)', edition: '2020', model: 'IMC' },
      plumbing: { name: '2020 Plumbing Code of New York State (IPC)', edition: '2020', model: 'IPC' },
    },
    climateZone: 'Zone 4A-6A (Mixed to Cold)',
    iceBarrierRequired: true,
    specialRules: ['nyc_dob_special_inspection', 'ice_barrier_mandatory_24_in', 'workers_comp_c105_mandatory'],
    basePermitFee: 105,
    estAverageFee: 185,
  },
  NC: {
    stateCode: 'NC',
    stateName: 'North Carolina',
    fips: '37',
    licensingBoard: 'North Carolina Licensing Board for General Contractors (NCLBGC)',
    licensingUrl: 'https://www.nclbgc.org',
    codes: {
      building: { name: '2018/2024 North Carolina Residential Code (NCRC / IRC)', edition: '2024', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2024 North Carolina Mechanical Code (IMC)', edition: '2024', model: 'IMC' },
      plumbing: { name: '2024 North Carolina Plumbing Code (IPC)', edition: '2024', model: 'IPC' },
    },
    climateZone: 'Zone 3A-4A (Warm-Humid / Mixed)',
    iceBarrierRequired: false,
    specialRules: ['coastal_wind_debris_zone', 'nclbgc_dollar_threshold_rules'],
    basePermitFee: 75,
    estAverageFee: 130,
  },
  ND: {
    stateCode: 'ND',
    stateName: 'North Dakota',
    fips: '38',
    licensingBoard: 'North Dakota Secretary of State / State Electrical Board / State Plumbing Board',
    licensingUrl: 'https://sos.nd.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC) (State Minimum)', edition: '2021', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 North Dakota State Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 6-7 (Very Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory_extended', 'extreme_cold_insulation'],
    basePermitFee: 65,
    estAverageFee: 110,
  },
  OH: {
    stateCode: 'OH',
    stateName: 'Ohio',
    fips: '39',
    licensingBoard: 'Ohio Department of Commerce (Division of Industrial Compliance / OCILB)',
    licensingUrl: 'https://com.ohio.gov/divisions-and-programs/industrial-compliance',
    codes: {
      building: { name: '2024 Residential Code of Ohio (RCO / 2021 IRC with OH Amendments)', edition: '2024', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2024 Ohio Mechanical Code (OMC / 2021 IMC)', edition: '2024', model: 'IMC' },
      plumbing: { name: '2024 Ohio Plumbing Code (OPC / 2021 IPC)', edition: '2024', model: 'IPC' },
    },
    climateZone: 'Zone 4A-5A (Mixed / Cold)',
    iceBarrierRequired: true,
    specialRules: ['ocilb_state_specialty_license_electrical_mechanical_plumbing', 'ice_barrier_mandatory'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  OK: {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    fips: '40',
    licensingBoard: 'Oklahoma Construction Industries Board (CIB)',
    licensingUrl: 'https://cib.ok.gov',
    codes: {
      building: { name: '2018/2021 Oklahoma Uniform Building Code Commission (OUBCC / IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 3A-4A (Tornado Alley / Mixed)',
    iceBarrierRequired: false,
    specialRules: ['cib_roofing_contractor_registration', 'enhanced_tornado_wind_nailing_pattern'],
    basePermitFee: 65,
    estAverageFee: 110,
  },
  OR: {
    stateCode: 'OR',
    stateName: 'Oregon',
    fips: '41',
    licensingBoard: 'Oregon Construction Contractors Board (CCB)',
    licensingUrl: 'https://www.oregon.gov/ccb',
    codes: {
      building: { name: '2023 Oregon Residential Specialty Code (ORSC / 2021 IRC)', edition: '2023', model: 'IRC' },
      electrical: { name: '2023 Oregon Electrical Specialty Code (OESC / 2023 NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2023 Oregon Mechanical Specialty Code (OMSC / 2021 IMC)', edition: '2023', model: 'IMC' },
      plumbing: { name: '2023 Oregon Plumbing Specialty Code (OPSC / 2021 UPC)', edition: '2023', model: 'UPC' },
    },
    climateZone: 'Zone 4C-5B (Marine / Cold)',
    iceBarrierRequired: true,
    specialRules: ['ccb_lead_based_paint_certification', 'wildfire_hazard_mitigation_roofing'],
    basePermitFee: 95,
    estAverageFee: 155,
  },
  PA: {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    fips: '42',
    licensingBoard: 'Pennsylvania Office of Attorney General (HIC Registration) / Dept of Labor & Industry (UCC)',
    licensingUrl: 'https://www.attorneygeneral.gov/protect-yourself/home-improvement-contractor',
    codes: {
      building: { name: 'Pennsylvania Uniform Construction Code (UCC / 2018/2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC / Philadelphia Plumbing Code)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A-5A (Mixed / Cold)',
    iceBarrierRequired: true,
    specialRules: ['pa_hic_statutory_contract_notice', 'ice_barrier_mandatory'],
    basePermitFee: 80,
    estAverageFee: 135,
  },
  RI: {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    fips: '44',
    licensingBoard: 'Rhode Island Contractors\' Registration and Licensing Board (CRLB)',
    licensingUrl: 'https://crb.ri.gov',
    codes: {
      building: { name: 'Rhode Island State Building Code SBC-2 (2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['crlb_registration_mandate', 'ice_barrier_mandatory'],
    basePermitFee: 75,
    estAverageFee: 130,
  },
  SC: {
    stateCode: 'SC',
    stateName: 'South Carolina',
    fips: '45',
    licensingBoard: 'South Carolina Department of Labor, Licensing and Regulation (LLR / Residential Builders Commission)',
    licensingUrl: 'https://llr.sc.gov/res',
    codes: {
      building: { name: '2021 South Carolina Residential Code (SCRC / 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 South Carolina Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 South Carolina Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 3A (Warm-Humid)',
    iceBarrierRequired: false,
    specialRules: ['coastal_high_wind_and_flood_zones'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  SD: {
    stateCode: 'SD',
    stateName: 'South Dakota',
    fips: '46',
    licensingBoard: 'South Dakota Department of Labor and Regulation / State Electrical & Plumbing Commissions',
    licensingUrl: 'https://dlr.sd.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 6 (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory', 'extreme_ground_snow_load'],
    basePermitFee: 65,
    estAverageFee: 105,
  },
  TN: {
    stateCode: 'TN',
    stateName: 'Tennessee',
    fips: '47',
    licensingBoard: 'Tennessee Board for Licensing Contractors (Department of Commerce and Insurance)',
    licensingUrl: 'https://www.tn.gov/commerce/regboards/contractors.html',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['home_improvement_license_threshold', 'ice_barrier_mandatory_east_tn'],
    basePermitFee: 70,
    estAverageFee: 120,
  },
  TX: {
    stateCode: 'TX',
    stateName: 'Texas',
    fips: '48',
    licensingBoard: 'Texas Department of Licensing and Regulation (TDLR) / Texas Dept of Insurance (TDI)',
    licensingUrl: 'https://www.tdlr.texas.gov',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC - Texas Minimum Standard)', edition: '2021', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC / TDLR Electrical Safety)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC / TDLR ACR)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC / TSBPE)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 2A-3A (Hot-Humid / Semi-Arid)',
    iceBarrierRequired: false,
    specialRules: [
      'tdi_windstorm_certification_catastrophe_area',
      'wpi_8_building_certificate_insurance_mandate',
      'tsbpe_state_plumbing_license',
    ],
    basePermitFee: 85,
    estAverageFee: 145,
  },
  UT: {
    stateCode: 'UT',
    stateName: 'Utah',
    fips: '49',
    licensingBoard: 'Utah Division of Professional Licensing (DOPL)',
    licensingUrl: 'https://dopl.utah.gov',
    codes: {
      building: { name: '2021 Utah Residential Code (2021 IRC with UT Amendments)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5B-6B (Cold-Dry / Alpine)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory', 'seismic_design_category_d_e', 'snow_load_drift'],
    basePermitFee: 80,
    estAverageFee: 135,
  },
  VT: {
    stateCode: 'VT',
    stateName: 'Vermont',
    fips: '50',
    licensingBoard: 'Vermont Division of Fire Safety / Secretary of State Office of Professional Regulation',
    licensingUrl: 'https://firesafety.vermont.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC) & Vermont Residential Building Energy Standards (RBES)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 6A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['vermont_rbes_energy_certificate', 'ice_barrier_mandatory_extended'],
    basePermitFee: 75,
    estAverageFee: 125,
  },
  VA: {
    stateCode: 'VA',
    stateName: 'Virginia',
    fips: '51',
    licensingBoard: 'Virginia Department of Professional and Occupational Regulation (DPOR / Board for Contractors)',
    licensingUrl: 'https://www.dpor.virginia.gov',
    codes: {
      building: { name: '2021 Virginia Uniform Statewide Building Code (VUSBC / 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 Virginia Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Virginia Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['dpor_class_a_b_c_contractor_license_threshold', 'ice_barrier_mandatory_piedmont_and_west'],
    basePermitFee: 80,
    estAverageFee: 140,
  },
  WA: {
    stateCode: 'WA',
    stateName: 'Washington',
    fips: '53',
    licensingBoard: 'Washington State Department of Labor & Industries (L&I / Contractor Registration)',
    licensingUrl: 'https://lni.wa.gov',
    codes: {
      building: { name: '2021 Washington State Residential Code (WAC 51-51 / 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020/2023 National Electrical Code (WAC 296-46B)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 Uniform Plumbing Code (UPC)', edition: '2021', model: 'UPC' },
    },
    climateZone: 'Zone 4C-5B (Marine / Cold)',
    iceBarrierRequired: true,
    specialRules: ['lni_contractor_bond_verification', 'wildland_urban_interface_wui_code'],
    basePermitFee: 95,
    estAverageFee: 165,
  },
  WV: {
    stateCode: 'WV',
    stateName: 'West Virginia',
    fips: '54',
    licensingBoard: 'West Virginia Division of Labor (Contractor Licensing Board)',
    licensingUrl: 'https://labor.wv.gov',
    codes: {
      building: { name: '2018/2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 5A (Cold)',
    iceBarrierRequired: true,
    specialRules: ['ice_barrier_mandatory'],
    basePermitFee: 65,
    estAverageFee: 105,
  },
  WI: {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    fips: '55',
    licensingBoard: 'Wisconsin Department of Safety and Professional Services (DSPS)',
    licensingUrl: 'https://dsps.wi.gov',
    codes: {
      building: { name: 'Wisconsin Uniform Dwelling Code (UDC / SPS 320-325)', edition: '2021', model: 'UDC' },
      electrical: { name: '2020/2023 Wisconsin Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: 'Wisconsin SPS 323 Mechanical Code', edition: '2021', model: 'IMC' },
      plumbing: { name: 'Wisconsin SPS 381-387 Uniform Plumbing Code', edition: '2021', model: 'WIPC' },
    },
    climateZone: 'Zone 6-7 (Cold / Very Cold)',
    iceBarrierRequired: true,
    specialRules: ['udc_credential_mandate_dwelling_contractor_qualifier', 'ice_barrier_mandatory_24_in'],
    basePermitFee: 80,
    estAverageFee: 130,
  },
  WY: {
    stateCode: 'WY',
    stateName: 'Wyoming',
    fips: '56',
    licensingBoard: 'Wyoming Department of Fire Prevention and Electrical Safety / Local Municipalities',
    licensingUrl: 'https://wsfm.wyo.gov',
    codes: {
      building: { name: '2021 International Residential Code (IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2023 National Electrical Code (NEC)', edition: '2023', model: 'NEC' },
      mechanical: { name: '2021 International Mechanical Code (IMC)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 International Plumbing Code (IPC)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 6-7 (Very Cold / Mountain)',
    iceBarrierRequired: true,
    specialRules: ['high_wind_fastening_provisions', 'heavy_snow_loads', 'ice_barrier_mandatory'],
    basePermitFee: 70,
    estAverageFee: 115,
  },
  DC: {
    stateCode: 'DC',
    stateName: 'District of Columbia',
    fips: '11',
    licensingBoard: 'Department of Buildings (DOB) / Board of Industrial Trades',
    licensingUrl: 'https://dob.dc.gov',
    codes: {
      building: { name: '2017/2021 District of Columbia Construction Codes (12A-12K DCMR / 2021 IRC)', edition: '2021', model: 'IRC' },
      electrical: { name: '2020 National Electrical Code (NEC / 12C DCMR)', edition: '2020', model: 'NEC' },
      mechanical: { name: '2021 District of Columbia Mechanical Code (12E DCMR)', edition: '2021', model: 'IMC' },
      plumbing: { name: '2021 District of Columbia Plumbing Code (12F DCMR)', edition: '2021', model: 'IPC' },
    },
    climateZone: 'Zone 4A (Mixed-Humid)',
    iceBarrierRequired: true,
    specialRules: ['historic_district_facade_review', 'dob_basic_business_license_bbl', 'ice_barrier_mandatory'],
    basePermitFee: 115,
    estAverageFee: 195,
  },
};

const STATE_NAMES_TO_CODE: Record<string, string> = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  'new hampshire': 'NH',
  'new jersey': 'NJ',
  'new mexico': 'NM',
  'new york': 'NY',
  'north carolina': 'NC',
  'north dakota': 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  'rhode island': 'RI',
  'south carolina': 'SC',
  'south dakota': 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  'west virginia': 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
  'district of columbia': 'DC',
  dc: 'DC',
};

/**
 * Normalizes any string representation of a state (abbreviation or name) to a 2-letter uppercase state code.
 */
export function normalizeStateCode(input?: string | null): string | null {
  if (!input) return null;
  const trimmed = input.trim();
  const upper = trimmed.toUpperCase();
  if (STATE_CODE_REGISTRY[upper]) return upper;

  const lower = trimmed.toLowerCase();
  if (STATE_NAMES_TO_CODE[lower]) return STATE_NAMES_TO_CODE[lower];

  return null;
}
